'use client';
import { useCallback,useEffect,useState } from 'react';
import Link from 'next/link';

type Row=Record<string,string|null>;
type Data={metrics:{registered:number;voters:number;suggestions:number;pendingContributions:number};users:Row[];suggestions:Row[];contributions:Row[];methods:Row[];settings:Record<string,string>};

export default function AdminPage(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[method,setMethod]=useState({label:'',url:'',instructions:''}),[manual,setManual]=useState({amount:'',target:'mobile-official',reference:''}),[settings,setSettings]=useState<Record<string,string>>({});
 const load=useCallback(()=>fetch('/api/admin/overview').then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);setSettings(b.settings||{});}).catch(e=>setError(e.message)),[]);
 useEffect(()=>{void load()},[load]);
 async function manage(body:Record<string,unknown>){await fetch('/api/admin/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load();}
 if(error)return <main className="admin-shell"><div className="admin-error">{error}<br/><Link href="/">Вернуться и войти</Link></div></main>;
 if(!data)return <main className="admin-shell"><div className="admin-loading">Загрузка…</div></main>;
 return <main className="admin-shell"><header className="admin-header"><Link href="/">← На сайт</Link><strong>World Clock · Админка</strong></header><section className="admin-intro"><p className="section-kicker">Закрытый раздел</p><h1>Люди, идеи и поддержка</h1><p>Автоматические платежи появляются сами. Переводы на карту можно внести вручную.</p></section>
 <section className="metric-grid"><article><strong>{data.metrics.registered}</strong><p>зарегистрировано</p></article><article><strong>{data.metrics.voters}</strong><p>проголосовало</p></article><article><strong>{data.metrics.suggestions}</strong><p>идей</p></article><article><strong>{data.metrics.pendingContributions}</strong><p>платежей обрабатывается</p></article></section>
 <Card title="Настройки сайта"><div className="response-list"><div className="response-row"><label>Цель помощи автору, центы USD<input value={settings.author_goal_cents||'300000'} onChange={e=>setSettings({...settings,author_goal_cents:e.target.value})}/></label><span>Собранную сумму нельзя менять вручную</span><button onClick={()=>manage({kind:'settings',values:settings})}>Сохранить</button></div><div className="response-row"><label>Ссылка на установщик<input value={settings.download_url||''} onChange={e=>setSettings({...settings,download_url:e.target.value})}/></label><label>Версия<input value={settings.download_version||''} onChange={e=>setSettings({...settings,download_version:e.target.value})}/></label><button onClick={()=>manage({kind:'settings',values:settings})}>Сохранить</button></div></div></Card>
 <Card title="Способы перевода"><p className="admin-note">Добавленное здесь появится в окне «Поддержать». Ссылка ведёт на оплату, инструкция показывает реквизиты.</p><div className="response-list">{data.methods.map(x=><div className="response-row" key={x.id}><div><strong>{x.label}</strong><p>{x.instructions}</p></div><a href={x.url||'#'}>{x.url||'Без ссылки'}</a><button onClick={()=>manage({kind:'method',...x,active:false})}>Скрыть</button></div>)}<div className="response-row"><input placeholder="Название способа" value={method.label} onChange={e=>setMethod({...method,label:e.target.value})}/><div><input placeholder="Ссылка на оплату (необязательно)" value={method.url} onChange={e=>setMethod({...method,url:e.target.value})}/><input placeholder="Реквизиты или короткая инструкция" value={method.instructions} onChange={e=>setMethod({...method,instructions:e.target.value})}/></div><button onClick={async()=>{await manage({kind:'method',...method});setMethod({label:'',url:'',instructions:''})}}>Добавить</button></div></div></Card>
 <Card title="Добавить полученный перевод"><p className="admin-note">Только для денег, которые уже поступили. Сумма на лицензии сразу попадёт в шкалу.</p><div className="response-row"><label>Сумма, USD<input inputMode="decimal" placeholder="25" value={manual.amount} onChange={e=>setManual({...manual,amount:e.target.value})}/></label><div><select value={manual.target} onChange={e=>setManual({...manual,target:e.target.value})}><option value="mobile-official">Лицензии iOS и Android</option><option value="author">Поддержка автора</option></select><input placeholder="Комментарий (необязательно)" value={manual.reference} onChange={e=>setManual({...manual,reference:e.target.value})}/></div><button onClick={async()=>{await manage({kind:'manual-contribution',...manual});setManual({...manual,amount:'',reference:''})}}>Добавить</button></div></Card>
 <Card title="Предложения пользователей"><div className="response-list">{data.suggestions.length?data.suggestions.map(x=><div className="response-row" key={x.id}><div><strong>{x.title}</strong><p>{x.name} · {x.email}</p><p>{x.problem}</p><small>{x.outcome}</small></div><strong>{x.status}</strong><div><button onClick={()=>manage({kind:'suggestion',id:x.id,status:'published'})}>Опубликовать</button> <button onClick={()=>manage({kind:'suggestion',id:x.id,status:'declined'})}>Скрыть</button></div></div>):<p className="admin-loading">Пока нет идей</p>}</div></Card>
 <Card title="Платёжный журнал"><div className="response-list">{data.contributions.length?data.contributions.map(x=><div className="response-row" key={x.id}><div><strong>${Number(x.amount_cents||0)/100} → {x.target_id}</strong><p>{x.provider||'legacy-manual'}</p><small>{x.reference}</small></div><strong>{x.status}</strong><small>{x.verified_at?new Date(x.verified_at).toLocaleString():'не подтверждён'}</small></div>):<p className="admin-loading">Пока нет платежей</p>}</div></Card>
 <Card title="Пользователи"><div className="response-list">{data.users.map(x=><div className="response-row" key={x.id}><div><strong>{x.name}</strong><p>{x.email}</p></div><span>{x.vote||'Без голоса'}</span><small>{x.last_seen&&new Date(x.last_seen).toLocaleString()}</small></div>)}</div></Card></main>;
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="responses-card"><header className="responses-heading"><h2>{title}</h2></header>{children}</section>}
