'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowDownToLine, ArrowRight, Check, Clock3, ExternalLink, Heart, Lightbulb, LogIn, LogOut, MessageSquarePlus, ShieldCheck, Smartphone, Sparkles } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { GoogleSignIn, type GoogleUser } from '@/components/google-sign-in';

type Localized = { ru: string; en: string };
type Idea = { id: string; status: string; goalCents: number; title: Localized; description: Localized; cost: Localized };
type Method = { id: string; label: string; url: string; instructions: string };
type Roadmap = { ideas: Idea[]; counts: Record<string,number>; funded: Record<string,number>; selected: string|null; settings: Record<string,string>; methods: Method[]; suggestions: Array<{id:string;title:string;problem:string;outcome:string}> };
type Modal = null|'auth'|'suggest'|'contribute'|'support';

const defaults: Roadmap={ideas:[],counts:{},funded:{},selected:null,settings:{},methods:[],suggestions:[]};
const strings={
  ru:{navRoadmap:'Планы',navIdeas:'Предложить идею',navSupport:'Поддержать',signin:'Войти',free:'Бесплатно — сегодня и всегда',headline:'Полезное время без подписки.',intro:'World Clock Widget и его основные функции полностью бесплатны. Пользуйтесь сколько угодно. Если приложение помогает вам, можно поддержать выбранную новую функцию или автора — только добровольно.',download:'Скачать для Windows',source:'Официальная версия на GitHub',roadmap:'Что дальше?',roadmapCopy:'Выберите одну функцию, которая нужна вам больше всего. Голос можно изменить в любой момент.',votes:'голосов',vote:'Голосовать',choice:'Ваш выбор',fund:'Поддержать функцию',goal:'Собрано',ideaTitle:'Предложить свою функцию',ideaCopy:'Опишите реальную проблему. После проверки идея сможет появиться в общем голосовании.',suggest:'Предложить идею',community:'Идеи сообщества',supportTitle:'Поддержать автора',supportCopy:'Сейчас я восстанавливаюсь после ишемического инфаркта мозжечка. Цель — оплатить медицинские счета, вернуть долги за лечение и продолжить восстановление. Приложение остаётся бесплатным независимо от результата сбора.',authorGoal:'Лечение и восстановление',support:'Поддержать',transparent:'Переводы добровольны. Поддержка функции показывает её приоритет и не является предзаказом. Платёжные данные сайт не хранит.',loginTitle:'Войти за несколько секунд',loginCopy:'Вход нужен, чтобы один человек учитывался один раз, а ваши идеи и поддержка были видны вам и автору.',problem:'Какую проблему это решит?',outcome:'Как должен выглядеть хороший результат?',send:'Отправить',thanks:'Спасибо. Запись отправлена автору.',amount:'Сумма в эквиваленте USD',reference:'Комментарий или последние цифры перевода',reported:'Отправить на подтверждение',methods:'Способы перевода',noMethods:'Реквизиты добавляются. Пока можно проголосовать или оставить идею.',statusFunding:'Собираем поддержку',statusIdea:'Идея'},
  en:{navRoadmap:'Roadmap',navIdeas:'Suggest an idea',navSupport:'Support',signin:'Sign in',free:'Free today and always',headline:'Useful time without a subscription.',intro:'World Clock Widget and its core features are completely free for as long as you need them. If it helps, you can voluntarily support a specific new feature or the person building it.',download:'Download for Windows',source:'Official GitHub release',roadmap:"What’s next?",roadmapCopy:'Choose the one feature you need most. You can change your vote at any time.',votes:'votes',vote:'Vote',choice:'Your choice',fund:'Fund this feature',goal:'Raised',ideaTitle:'Suggest a feature',ideaCopy:'Describe a real problem. After review, the idea can become part of the public vote.',suggest:'Suggest an idea',community:'Community ideas',supportTitle:'Support the author',supportCopy:'I am currently recovering from an ischemic cerebellar stroke. The goal is to cover medical bills, repay treatment debt and continue recovery. The app stays free regardless of the result.',authorGoal:'Treatment and recovery',support:'Support',transparent:'Contributions are voluntary. Funding a feature signals priority and is not a preorder. This site never stores card details.',loginTitle:'Sign in in seconds',loginCopy:'Sign-in keeps voting fair and lets the author connect your ideas and reported contributions to you.',problem:'What problem would this solve?',outcome:'What would a good result look like?',send:'Send',thanks:'Thank you. The author has received it.',amount:'Amount in USD equivalent',reference:'Note or last transfer digits',reported:'Send for confirmation',methods:'Ways to contribute',noMethods:'Transfer details are being added. You can still vote or suggest an idea.',statusFunding:'Funding',statusIdea:'Idea'}
};

export default function Home(){
  const [lang,setLang]=useState<'ru'|'en'>('ru'),[data,setData]=useState<Roadmap>(defaults),[user,setUser]=useState<GoogleUser|null>(null),[modal,setModal]=useState<Modal>(null),[pendingVote,setPendingVote]=useState<string|null>(null),[target,setTarget]=useState('author'),[message,setMessage]=useState(''),[busy,setBusy]=useState(true);
  const [suggestion,setSuggestion]=useState({title:'',problem:'',outcome:''}),[contribution,setContribution]=useState({amount:'',reference:''});
  const t=strings[lang];
  const load=useCallback(async()=>{const [roadmap,auth]=await Promise.all([fetch('/api/roadmap').then(r=>r.json()),fetch('/api/auth/me').then(r=>r.json())]);setData(roadmap);setUser(auth.user||null);setBusy(false);},[]);
  useEffect(()=>{const saved=localStorage.getItem('wc-lang');if(saved==='en')setLang('en');void load().catch(()=>setBusy(false));},[load]);
  const chooseLang=(value:'ru'|'en')=>{setLang(value);localStorage.setItem('wc-lang',value);document.documentElement.lang=value;};
  const totalVotes=useMemo(()=>Object.values(data.counts).reduce((a,b)=>a+b,0),[data.counts]);
  const download=data.settings.download_url||'https://github.com/CandFlip/world-clock-widget/releases/download/windows-v1.1.77/WorldClockWidget-Setup-v1.1.77.exe';
  const version=data.settings.download_version||'v1.1.77';
  async function saveVote(id:string){setBusy(true);const response=await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({optionId:id})});if(response.ok)await load();else setMessage(lang==='ru'?'Не удалось сохранить голос.':'Could not save the vote.');setBusy(false);}
  async function vote(id:string){if(!user){setPendingVote(id);setModal('auth');return;}await saveVote(id);}
  function signedIn(next:GoogleUser){setUser(next);setModal(null);if(pendingVote){const id=pendingVote;setPendingVote(null);void saveVote(id);}}
  async function sendSuggestion(){const response=await fetch('/api/suggestions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(suggestion)});if(response.status===401){setModal('auth');return;}if(response.ok){setSuggestion({title:'',problem:'',outcome:''});setMessage(t.thanks);setModal(null);}else setMessage(lang==='ru'?'Проверьте заполнение формы.':'Please check the form.');}
  function openSupport(id:string){setTarget(id);setModal('support');}
  async function reportContribution(){const response=await fetch('/api/contributions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetId:target,amount:Number(contribution.amount),currency:'USD',reference:contribution.reference})});if(response.status===401){setModal('auth');return;}if(response.ok){setContribution({amount:'',reference:''});setMessage(t.thanks);setModal(null);}else setMessage(lang==='ru'?'Проверьте сумму.':'Please check the amount.');}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});setUser(null);}
  const authorGoal=Number(data.settings.author_goal_cents||300000),authorRaised=Number(data.settings.author_raised_cents||0)+(data.funded.author||0);
  return <main className="site-shell">
    <nav className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Clock3/></span><span>World Clock</span></a><div className="nav-links"><a href="#roadmap">{t.navRoadmap}</a><button onClick={()=>setModal('suggest')}>{t.navIdeas}</button><a href="#support">{t.navSupport}</a></div><div className="account-area"><div className="language"><button className={lang==='ru'?'active':''} onClick={()=>chooseLang('ru')}>RU</button><button className={lang==='en'?'active':''} onClick={()=>chooseLang('en')}>EN</button></div>{user?<>{user.isAdmin&&<Link className="admin-link" href="/admin"><ShieldCheck size={15}/></Link>}<span className="user-chip">{user.name}</span><button onClick={logout} aria-label="Sign out"><LogOut size={16}/></button></>:<button className="signin-link" onClick={()=>setModal('auth')}><LogIn size={15}/>{t.signin}</button>}</div></nav>

    <section className="hero" id="top"><div className="free-pill"><Sparkles size={15}/>{t.free}</div><h1>{t.headline}</h1><p>{t.intro}</p><div className="hero-actions"><a className="primary-action" href={download}><ArrowDownToLine/>{t.download}<span>{version}</span></a><a className="text-action" href="https://github.com/CandFlip/world-clock-widget/releases" target="_blank" rel="noreferrer">{t.source}<ExternalLink/></a></div><div className="promise"><strong>0 ₽</strong><span>{lang==='ru'?'Нет платных уровней, пробного периода или заблокированных основных функций.':'No paid tiers, trial period or locked core features.'}</span></div></section>

    <section className="roadmap-section" id="roadmap"><header className="section-heading"><div><p className="section-kicker">{totalVotes} {t.votes}</p><h2>{t.roadmap}</h2><p>{t.roadmapCopy}</p></div><button className="secondary-action" onClick={()=>setModal('suggest')}><MessageSquarePlus/>{t.suggest}</button></header><div className="idea-list">{data.ideas.map((idea,index)=>{const votes=data.counts[idea.id]||0,funded=data.funded[idea.id]||0,percent=idea.goalCents?Math.min(100,Math.round(funded/idea.goalCents*100)):0,selected=data.selected===idea.id;return <article className={`idea-card ${index===0?'featured':''}`} key={idea.id}><div className="idea-number">0{index+1}</div><div className="idea-copy"><div className="idea-meta"><span>{idea.status==='funding'?t.statusFunding:t.statusIdea}</span><small>{idea.cost[lang]}</small></div><h3>{idea.title[lang]}</h3><p>{idea.description[lang]}</p>{idea.goalCents>0&&<div className="funding"><div><span>{t.goal}</span><strong>${(funded/100).toFixed(0)} / ${(idea.goalCents/100).toFixed(0)}</strong></div><div className="track"><i style={{width:`${percent}%`}}/></div></div>}</div><div className="idea-actions"><button className={selected?'selected':''} onClick={()=>vote(idea.id)} disabled={busy}>{selected?<Check/>:<Lightbulb/>}{selected?t.choice:t.vote}<span>{votes}</span></button>{idea.goalCents>0&&<button onClick={()=>openSupport(idea.id)}><Heart/>{t.fund}</button>}</div></article>})}</div>
      {data.suggestions.length>0&&<div className="community"><p className="section-kicker">{t.community}</p>{data.suggestions.map(item=><article key={item.id}><h3>{item.title}</h3><p>{item.problem}</p>{item.outcome&&<small>{item.outcome}</small>}</article>)}</div>}<output className="status-message">{message}</output></section>

    <section className="support-card" id="support"><div className="support-story"><p className="section-kicker">{t.authorGoal}</p><h2>{t.supportTitle}</h2><p>{data.settings[`author_story_${lang}`]||t.supportCopy}</p><p className="transparency">{t.transparent}</p></div><div className="support-panel"><div className="support-total"><strong>${(authorRaised/100).toLocaleString('en-US')}</strong><span>/ ${(authorGoal/100).toLocaleString('en-US')}</span></div><div className="track large"><i style={{width:`${Math.min(100,authorRaised/authorGoal*100)}%`}}/></div><button className="primary-action" onClick={()=>openSupport('author')}><Heart/>{t.support}</button></div></section>
    <footer><span>World Clock Widget · {t.free}</span><a href="https://github.com/CandFlip/world-clock-widget" target="_blank" rel="noreferrer">GitHub <ExternalLink/></a></footer>

    <Dialog open={modal==='auth'} onOpenChange={open=>!open&&setModal(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{t.loginTitle}</DialogTitle><DialogDescription>{t.loginCopy}</DialogDescription></DialogHeader><GoogleSignIn lang={lang} onSignedIn={signedIn}/></DialogContent></Dialog>
    <Dialog open={modal==='suggest'} onOpenChange={open=>!open&&setModal(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{t.ideaTitle}</DialogTitle><DialogDescription>{t.ideaCopy}</DialogDescription></DialogHeader><label><span>{lang==='ru'?'Короткое название':'Short title'}</span><input maxLength={100} value={suggestion.title} onChange={e=>setSuggestion({...suggestion,title:e.target.value})}/></label><label><span>{t.problem}</span><Textarea maxLength={800} value={suggestion.problem} onChange={e=>setSuggestion({...suggestion,problem:e.target.value})}/></label><label><span>{t.outcome}</span><Textarea maxLength={800} value={suggestion.outcome} onChange={e=>setSuggestion({...suggestion,outcome:e.target.value})}/></label><button className="primary-action" onClick={sendSuggestion}><ArrowRight/>{t.send}</button></DialogContent></Dialog>
    <Dialog open={modal==='support'} onOpenChange={open=>!open&&setModal(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{target==='author'?t.supportTitle:t.fund}</DialogTitle><DialogDescription>{t.transparent}</DialogDescription></DialogHeader><h3>{t.methods}</h3>{data.methods.length?<div className="method-list">{data.methods.map(method=><div key={method.id}><strong>{method.label}</strong><p>{method.instructions}</p>{method.url&&<a href={method.url} target="_blank" rel="noreferrer">{t.support}<ExternalLink/></a>}</div>)}</div>:<p className="empty-note">{t.noMethods}</p>}<label><span>{t.amount}</span><input type="number" min="1" step="1" value={contribution.amount} onChange={e=>setContribution({...contribution,amount:e.target.value})}/></label><label><span>{t.reference}</span><input maxLength={300} value={contribution.reference} onChange={e=>setContribution({...contribution,reference:e.target.value})}/></label><button className="primary-action" disabled={!contribution.amount} onClick={reportContribution}><Check/>{t.reported}</button></DialogContent></Dialog>
  </main>;
}
