'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowDownToLine, Check, Clock3, ExternalLink, Heart, Lightbulb, LogIn, LogOut, MessageSquarePlus, ShieldCheck, Smartphone } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { GoogleSignIn, type GoogleUser } from '@/components/google-sign-in';

type Localized = { ru: string; en: string };
type Idea = { id: string; status: string; goalCents: number; title: Localized; description: Localized; cost: Localized };
type Method = { id: string; label: string; url: string; instructions: string };
type Roadmap = { ideas: Idea[]; counts: Record<string, number>; funded: Record<string, number>; selected: string | null; settings: Record<string, string>; methods: Method[]; suggestions: Array<{ id: string; title: string; problem: string; outcome: string }> };
type Modal = null | 'auth' | 'suggest' | 'support';

const defaults: Roadmap = { ideas: [], counts: {}, funded: {}, selected: null, settings: {}, methods: [], suggestions: [] };
const strings = {
  ru: {
    navRoadmap: 'Планы', navIdeas: 'Предложить идею', navSupport: 'Поддержать', signin: 'Войти', eyebrow: 'Бесплатный виджет мирового времени', headline: 'Время разных городов — рядом, когда оно нужно.', intro: 'World Clock Widget помогает планировать звонки, встречи и напоминания между часовыми поясами. Без подписки и платных уровней.', download: 'Скачать для Windows', source: 'Открыть страницу релизов', promise: 'Приложение бесплатно. Поддержка проекта не влияет на доступ к функциям.', roadmap: 'Что сделать следующим?', roadmapCopy: 'Выберите одну функцию, которая пригодится вам больше всего. Голос можно изменить.', votes: 'голосов', vote: 'Голосовать', choice: 'Ваш выбор', ideaTitle: 'Предложить функцию', ideaCopy: 'Опишите задачу, которую новая функция должна решить.', suggest: 'Предложить идею', community: 'Идеи сообщества', mobileNote: 'Для официального выпуска на телефонах нужны аккаунты разработчика Google Play и Apple.', verified: 'Подтверждено поступлениями', licenseGoal: 'Лицензии для iOS и Android', storyKicker: 'Личная поддержка', supportTitle: 'Восстановление после инсульта', supportCopy: 'В сентябре 2026 года я попал в больницу после ишемического инфаркта мозжечка. Поддержка в этом разделе помогает оплачивать лечение, восстановление и связанные с ними долги.', support: 'Поддержать', transparent: 'Публичная сумма меняется только после фактического подтверждения платежа. Заявления пользователей и ручные правки в неё не попадают.', photoRoom: 'В больничной палате, сентябрь 2026', photoIv: 'Во время лечения в больнице', photoMri: 'Снимок МРТ, сделанный во время обследования', photoReport: 'Заключение МРТ из больницы', photoTranslation: 'Перевод результата обследования', loginTitle: 'Войти за несколько секунд', loginCopy: 'Вход нужен только для честного голосования и отправки предложений.', problem: 'Какую проблему это решит?', outcome: 'Как должен выглядеть хороший результат?', send: 'Отправить', thanks: 'Спасибо. Запись отправлена.', methods: 'Способы поддержки', noMethods: 'Безопасные способы оплаты подключаются. Я опубликую их только после проверки автоматического учёта поступлений.', paymentNote: 'Вы переходите на страницу банка или кошелька. Данные карты на этом сайте не вводятся и не хранятся.', statusFunding: 'Ближайший шаг', statusIdea: 'Идея', footer: 'World Clock Widget · бесплатно для всех',
  },
  en: {
    navRoadmap: 'Roadmap', navIdeas: 'Suggest an idea', navSupport: 'Support', signin: 'Sign in', eyebrow: 'A free world clock widget', headline: 'The time in every city, right when you need it.', intro: 'World Clock Widget helps plan calls, meetings and reminders across time zones. No subscription and no paid tiers.', download: 'Download for Windows', source: 'Open the releases page', promise: 'The app is free. Supporting the project never changes access to its features.', roadmap: 'What should come next?', roadmapCopy: 'Choose the one feature that would help you most. You can change your vote.', votes: 'votes', vote: 'Vote', choice: 'Your choice', ideaTitle: 'Suggest a feature', ideaCopy: 'Describe the problem the new feature should solve.', suggest: 'Suggest an idea', community: 'Community ideas', mobileNote: 'Official phone releases require Google Play and Apple developer accounts.', verified: 'Verified incoming payments', licenseGoal: 'iOS and Android licenses', storyKicker: 'Personal support', supportTitle: 'Recovering after a stroke', supportCopy: 'In September 2026 I was hospitalized after an ischemic cerebellar stroke. Support here helps cover treatment, recovery and related debt.', support: 'Support', transparent: 'The public total changes only after a payment is actually verified. User reports and manual edits are never counted.', photoRoom: 'In the hospital, September 2026', photoIv: 'During hospital treatment', photoMri: 'MRI scan from the examination', photoReport: 'Hospital MRI report', photoTranslation: 'Translation of the examination result', loginTitle: 'Sign in in seconds', loginCopy: 'Sign-in is only needed for fair voting and suggestions.', problem: 'What problem would this solve?', outcome: 'What would a good result look like?', send: 'Send', thanks: 'Thank you. Your message was sent.', methods: 'Ways to support', noMethods: 'Secure payment options are being connected. They will appear only after automatic payment verification has been tested.', paymentNote: 'You will continue on the bank or wallet page. Card details are never entered or stored on this site.', statusFunding: 'Next step', statusIdea: 'Idea', footer: 'World Clock Widget · free for everyone',
  },
};

export default function Home() {
  const [lang, setLang] = useState<'ru' | 'en'>('ru'), [data, setData] = useState<Roadmap>(defaults), [user, setUser] = useState<GoogleUser | null>(null), [modal, setModal] = useState<Modal>(null), [pendingVote, setPendingVote] = useState<string | null>(null), [message, setMessage] = useState(''), [busy, setBusy] = useState(true);
  const [suggestion, setSuggestion] = useState({ title: '', problem: '', outcome: '' });
  const t = strings[lang];
  const load = useCallback(async () => { const [roadmap, auth] = await Promise.all([fetch('/api/roadmap').then((r) => r.json()), fetch('/api/auth/me').then((r) => r.json())]); setData(roadmap); setUser(auth.user || null); setBusy(false); }, []);
  useEffect(() => { const saved = localStorage.getItem('wc-lang'); if (saved === 'en') setLang('en'); void load().catch(() => setBusy(false)); }, [load]);
  const chooseLang = (value: 'ru' | 'en') => { setLang(value); localStorage.setItem('wc-lang', value); document.documentElement.lang = value; };
  const totalVotes = useMemo(() => Object.values(data.counts).reduce((a, b) => a + b, 0), [data.counts]);
  const download = data.settings.download_url || 'https://github.com/CandFlip/world-clock-widget/releases/download/windows-v1.1.77/WorldClockWidget-Setup-v1.1.77.exe', version = data.settings.download_version || 'v1.1.77', mobileRaised = data.funded['mobile-official'] || 0, authorRaised = data.funded.author || 0, authorGoal = Number(data.settings.author_goal_cents || 300000);
  async function saveVote(id: string) { setBusy(true); const response = await fetch('/api/votes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ optionId: id }) }); if (response.ok) await load(); else setMessage(lang === 'ru' ? 'Не удалось сохранить голос.' : 'Could not save the vote.'); setBusy(false); }
  async function vote(id: string) { if (!user) { setPendingVote(id); setModal('auth'); return; } await saveVote(id); }
  function signedIn(next: GoogleUser) { setUser(next); setModal(null); if (pendingVote) { const id = pendingVote; setPendingVote(null); void saveVote(id); } }
  async function sendSuggestion() { const response = await fetch('/api/suggestions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(suggestion) }); if (response.status === 401) { setModal('auth'); return; } if (response.ok) { setSuggestion({ title: '', problem: '', outcome: '' }); setMessage(t.thanks); setModal(null); } else setMessage(lang === 'ru' ? 'Проверьте заполнение формы.' : 'Please check the form.'); }
  async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); setUser(null); }
  return <main className="site-shell">
    <nav className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Clock3 /></span><span>World Clock</span></a><div className="nav-links"><a href="#roadmap">{t.navRoadmap}</a><button onClick={() => setModal('suggest')}>{t.navIdeas}</button><a href="#support">{t.navSupport}</a></div><div className="account-area"><div className="language"><button className={lang === 'ru' ? 'active' : ''} onClick={() => chooseLang('ru')}>RU</button><button className={lang === 'en' ? 'active' : ''} onClick={() => chooseLang('en')}>EN</button></div>{user ? <><span className="user-chip">{user.name}</span>{user.isAdmin && <Link className="admin-link" href="/admin" aria-label="Admin"><ShieldCheck size={15} /></Link>}<button onClick={logout} aria-label="Sign out"><LogOut size={16} /></button></> : <button className="signin-link" onClick={() => setModal('auth')}><LogIn size={15} />{t.signin}</button>}</div></nav>
    <section className="hero" id="top"><p className="hero-kicker">{t.eyebrow}</p><h1>{t.headline}</h1><p className="hero-copy">{t.intro}</p><div className="hero-actions"><a className="primary-action" href={download}><ArrowDownToLine />{t.download}<span>{version}</span></a><a className="text-action" href="https://github.com/CandFlip/world-clock-widget/releases" target="_blank" rel="noreferrer">{t.source}<ExternalLink /></a></div><p className="quiet-promise">{t.promise}</p></section>
    <section className="roadmap-section" id="roadmap"><header className="section-heading"><div><p className="section-kicker">{totalVotes} {t.votes}</p><h2>{t.roadmap}</h2><p>{t.roadmapCopy}</p></div><button className="secondary-action" onClick={() => setModal('suggest')}><MessageSquarePlus />{t.suggest}</button></header><div className="idea-list">{data.ideas.map((idea, index) => { const votes = data.counts[idea.id] || 0, selected = data.selected === idea.id; return <article className={`idea-card ${index === 0 ? 'featured' : ''}`} key={idea.id}><div className="idea-number">0{index + 1}</div><div className="idea-copy"><div className="idea-meta"><span>{idea.status === 'funding' ? t.statusFunding : t.statusIdea}</span>{idea.id === 'mobile-official' && <small><Smartphone size={14} />{t.mobileNote}</small>}</div><h3>{idea.title[lang]}</h3><p>{idea.description[lang]}</p>{idea.id === 'mobile-official' && <div className="license-line"><span>{t.licenseGoal}</span><span>{t.verified}: <strong>${(mobileRaised / 100).toFixed(0)} / $124</strong></span></div>}</div><div className="idea-actions"><button className={selected ? 'selected' : ''} onClick={() => vote(idea.id)} disabled={busy}>{selected ? <Check /> : <Lightbulb />}{selected ? t.choice : t.vote}<span>{votes}</span></button></div></article>; })}</div>{data.suggestions.length > 0 && <div className="community"><p className="section-kicker">{t.community}</p>{data.suggestions.map((item) => <article key={item.id}><h3>{item.title}</h3><p>{item.problem}</p>{item.outcome && <small>{item.outcome}</small>}</article>)}</div>}<output className="status-message">{message}</output></section>
    <section className="support-section" id="support"><div className="story-collage" aria-label={t.supportTitle}><figure className="story-main"><img src="/story/hospital-room.jpg" alt={t.photoRoom} /><figcaption>{t.photoRoom}</figcaption></figure><figure><img src="/story/hospital-iv.jpg" alt={t.photoIv} /><figcaption>{t.photoIv}</figcaption></figure><figure><img src="/story/mri-scan.jpg" alt={t.photoMri} /><figcaption>{t.photoMri}</figcaption></figure><figure><img src="/story/mri-report.jpg" alt={t.photoReport} /><figcaption>{t.photoReport}</figcaption></figure><figure><img src="/story/translated-result.jpg" alt={t.photoTranslation} /><figcaption>{t.photoTranslation}</figcaption></figure></div><div className="support-story"><p className="section-kicker">{t.storyKicker}</p><h2>{t.supportTitle}</h2><p>{data.settings[`author_story_${lang}`] || t.supportCopy}</p><div className="support-total"><span>{t.verified}</span><strong>${(authorRaised / 100).toLocaleString('en-US')} <small>/ ${(authorGoal / 100).toLocaleString('en-US')}</small></strong></div><button className="support-action" onClick={() => setModal('support')}><Heart />{t.support}</button><p className="transparency">{t.transparent}</p></div></section>
    <footer><span>{t.footer}</span><a href="https://github.com/CandFlip/world-clock-widget" target="_blank" rel="noreferrer">GitHub <ExternalLink /></a></footer>
    <Dialog open={modal === 'auth'} onOpenChange={(open) => !open && setModal(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{t.loginTitle}</DialogTitle><DialogDescription>{t.loginCopy}</DialogDescription></DialogHeader><GoogleSignIn lang={lang} onSignedIn={signedIn} /></DialogContent></Dialog>
    <Dialog open={modal === 'suggest'} onOpenChange={(open) => !open && setModal(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{t.ideaTitle}</DialogTitle><DialogDescription>{t.ideaCopy}</DialogDescription></DialogHeader><label><span>{lang === 'ru' ? 'Короткое название' : 'Short title'}</span><input maxLength={100} value={suggestion.title} onChange={(e) => setSuggestion({ ...suggestion, title: e.target.value })} /></label><label><span>{t.problem}</span><Textarea maxLength={800} value={suggestion.problem} onChange={(e) => setSuggestion({ ...suggestion, problem: e.target.value })} /></label><label><span>{t.outcome}</span><Textarea maxLength={800} value={suggestion.outcome} onChange={(e) => setSuggestion({ ...suggestion, outcome: e.target.value })} /></label><button className="primary-action" onClick={sendSuggestion}>{t.send}</button></DialogContent></Dialog>
    <Dialog open={modal === 'support'} onOpenChange={(open) => !open && setModal(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{t.methods}</DialogTitle><DialogDescription>{t.paymentNote}</DialogDescription></DialogHeader>{data.methods.length ? <div className="method-list">{data.methods.map((method) => <div key={method.id}><strong>{method.label}</strong><p>{method.instructions}</p>{method.url && <a href={method.url} target="_blank" rel="noreferrer">{t.support}<ExternalLink /></a>}</div>)}</div> : <p className="empty-note">{t.noMethods}</p>}<p className="modal-transparency"><ShieldCheck size={16} />{t.transparent}</p></DialogContent></Dialog>
  </main>;
}
