const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({
  window: {chrome: {webview: {postMessage() {}, addEventListener() {}}}},
  document: {querySelector: () => ({}), querySelectorAll: () => [], addEventListener() {}},
  Intl, Date, structuredClone, crypto: require('node:crypto').webcrypto,
});
vm.runInContext(fs.readFileSync(__dirname + '/ui/suncalc.js', 'utf8'), context);
vm.runInContext(fs.readFileSync(__dirname + '/ui/reminder_ui.js', 'utf8'), context);
vm.runInContext(fs.readFileSync(__dirname + '/ui/app.js', 'utf8'), context);
const run = script => vm.runInContext(script, context);
run("config.settings.time_format='24'");
assert.deepEqual(Array.from(run("[0,6,12,18,24].map(h => timelineCaption(h,new Date('2026-09-26T19:24:00Z'),'Asia/Bangkok'))")), ['02','08','14','20','02'].map(h => `${h}<small class="timeline-minutes">:24</small>`));
assert.equal(run("timelineCaption(6,new Date('2026-09-26T19:59:00Z'),'Asia/Bangkok')"), '08<small class="timeline-minutes">:59</small>');
assert.equal(run("timelineCaption(6,new Date('2026-09-26T20:00:00Z'),'Asia/Bangkok')"), '09<small class="timeline-minutes">:00</small>');
assert.deepEqual(Array.from(run("[6,12,18,24].map(h => timelineHour(h,new Date('2026-09-26T19:24:00Z'),'Asia/Bangkok'))")), ['08','14','20','02']);
assert.equal(run("timelineHour(6,new Date('2026-09-26T19:24:00Z'),'Asia/Kathmandu')"), '07');
assert.equal(run("timelineHour(6,new Date('2026-03-08T05:30:00Z'),'America/New_York')"), '07');
run("config.settings.time_format='12'");
assert.equal(run("timelineHour(12,new Date('2026-09-26T19:24:00Z'),'Asia/Bangkok')"), '2 PM');
run("config.settings.time_format='system'");
const css = fs.readFileSync(__dirname + '/ui/style.css', 'utf8');
const appSource = fs.readFileSync(__dirname + '/ui/app.js', 'utf8');
assert.match(appSource, /<section class="\$\{quickClass\}" id="quickSection">\s*<div class="timeline-actions">[\s\S]*?id="meetingToggle"[\s\S]*?id="meetingCopy"/);
assert.equal(appSource.includes('quickClass = offset > 0 || quickAtNowOpen || meetingMode'), true);
assert.equal(run('strings.ru.citySettings'), 'Имена и графики городов');
assert.equal(run('strings.en.citySettings'), 'City names and schedules');
assert.equal(run('strings.ru.nameAndSchedule'), 'Имя и график');
assert.ok(run("openSettings.toString().includes('id=\"citySettings\"')"));
assert.ok(run("openSettings.toString().includes('id=\"base\"')"));
assert.ok(run("openSettings.toString().indexOf('id=\"theme\"') < openSettings.toString().indexOf('id=\"timeFormat\"') && openSettings.toString().indexOf('id=\"timeFormat\"') < openSettings.toString().indexOf('id=\"base\"')"));
assert.equal(run("openSettings.toString().includes('id=\"typicalSchedule\"')"), false);
assert.equal(run("openSettings.toString().includes('id=\"baseSchedule\"')"), false);
assert.equal(run("openCitySettingsList.toString().includes('id=\"selectBaseCity\"')"), false);
assert.ok(run("openCitySettingsList.toString().includes('id=\"baseSchedule\"')"));
assert.ok(run("openCitySettingsList.toString().includes('id=\"typicalSchedule\"')"));
assert.equal(run("openCityActions.toString().includes('id=\"renameCity\"')"), false);
assert.equal(run('hotkeyLabel()'), 'Alt+Space');
assert.equal(run("hotkeyLabel({modifiers:2,key:112})"), 'Ctrl+F1');
assert.equal(run("hotkeyLabel({modifiers:0,key:65})"), 'A');
assert.equal(run("hotkeyFromEvent({code:'KeyK',key:'л',ctrlKey:true,altKey:false,shiftKey:true,metaKey:false})?.key"), 75);
assert.equal(run("hotkeyFromEvent({code:'F11',key:'F11',ctrlKey:false,altKey:false,shiftKey:false,metaKey:false})?.key"), 122);
assert.equal(run("hotkeyFromEvent({code:'F12',key:'F12',ctrlKey:false,altKey:false,shiftKey:false,metaKey:false})"), null);
assert.equal(run("hotkeyLabel({modifiers:2,key:191})"), 'Ctrl+/');
assert.equal(run("hotkeyFromEvent({code:'Space',key:' ',ctrlKey:false,altKey:false,shiftKey:false,metaKey:false})"), null);
assert.equal(run("hotkeyFromEvent({code:'KeyT',key:'t',ctrlKey:false,altKey:false,shiftKey:false,metaKey:true})"), null);
assert.equal(run("offsetHours('Asia/Kolkata', new Date('2026-09-05T00:00:00Z'))"), 5.5);
assert.equal(run("offsetHours('Asia/Kathmandu', new Date('2026-09-05T00:00:00Z'))"), 5.75);
assert.equal(run("epochAt('2026-09-05T12:15', 'Asia/Kathmandu')"), Date.parse('2026-09-05T06:30:00Z'));
assert.equal(run("epochAt('2026-01-05T12:00', 'America/New_York')"), Date.parse('2026-01-05T17:00:00Z'));
assert.equal(run("epochAt('2026-07-05T12:00', 'America/New_York')"), Date.parse('2026-07-05T16:00:00Z'));
assert.ok(Math.abs(run('referenceTimestamp()') - Date.now()) < 1000);
assert.equal(run('sliderPosition(0, 400)'), 10);
assert.equal(run('sliderPosition(6, 400)'), 105);
assert.equal(run('sliderPosition(12, 400)'), 200);
assert.equal(run('sliderPosition(24, 400)'), 390);
assert.equal(run('shiftCaption(.25)'), '+15 мин');
assert.equal(run('shiftCaption(4.5)'), '+4 ч 30 мин');
assert.equal(run("availabilityAt(defaultAvailability, 7 * 60)"), 'okay');
assert.equal(run("availabilityAt(defaultAvailability, 9 * 60)"), 'working');
assert.equal(run("availabilityAt(defaultAvailability, 18 * 60)"), 'okay');
assert.equal(run("availabilityAt(defaultAvailability, 22 * 60)"), 'dnd');
assert.equal(run("availabilityAt({okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}, 30)"), 'okay');
assert.equal(run("availabilityAt({okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}, 120)"), 'dnd');
assert.equal(run("meetingQuality(Date.parse('2026-10-06T06:00:00Z'), [{zone:'Europe/Moscow',schedule:defaultAvailability},{zone:'Asia/Bangkok',schedule:defaultAvailability}])"), 0);
assert.equal(run("findMeetingTimes([{zone:'Europe/Moscow',schedule:defaultAvailability},{zone:'Asia/Bangkok',schedule:defaultAvailability}], Date.parse('2026-10-06T05:45:00Z')).best.at"), Date.parse('2026-10-06T06:00:00Z'));
assert.equal(run("findMeetingTimes([{zone:'Europe/Moscow',schedule:defaultAvailability},{zone:'Asia/Bangkok',schedule:{okayStart:'07:00',workingStart:'14:00',workingEnd:'18:00',dndStart:'22:00'}}], Date.parse('2026-10-06T05:45:00Z')).earlier.at"), Date.parse('2026-10-06T05:45:00Z'));
assert.equal(run("findMeetingTimes([{zone:'Europe/Moscow',schedule:defaultAvailability},{zone:'Asia/Bangkok',schedule:{okayStart:'07:00',workingStart:'14:00',workingEnd:'18:00',dndStart:'22:00'}}], Date.parse('2026-10-06T05:45:00Z')).best.at"), Date.parse('2026-10-06T07:00:00Z'));
assert.equal(run("findMeetingTimes([{zone:'UTC',schedule:{okayStart:'09:00',workingStart:'10:00',workingEnd:'11:00',dndStart:'12:00'}},{zone:'Pacific/Auckland',schedule:{okayStart:'09:00',workingStart:'10:00',workingEnd:'11:00',dndStart:'12:00'}}], Date.parse('2026-10-06T00:00:00Z')).best"), null);
assert.ok(run("meetingCopyText(Date.parse('2026-10-06T06:00:00Z'), [{key:'Europe/Moscow',zone:'Europe/Moscow'},{key:'Asia/Vladivostok',zone:'Asia/Vladivostok'}])").includes('Moscow'));
assert.ok(run("meetingCopyText(Date.parse('2026-10-06T06:00:00Z'), [{key:'Europe/Moscow',zone:'Europe/Moscow'},{key:'Asia/Vladivostok',zone:'Asia/Vladivostok'}])").includes('Vladivostok'));
run("config.settings.time_format='24'");
const copiedMeeting = run("meetingCopyText(Date.parse('2026-10-09T11:00:00Z'), [{key:'Europe/Moscow',zone:'Europe/Moscow'},{key:'Asia/Vladivostok',zone:'Asia/Vladivostok'}])");
const copiedLines = copiedMeeting.split('\n');
assert.equal(copiedLines.length, 2);
assert.match(copiedLines[0], /^Moscow — .*14:00$/);
assert.match(copiedLines[1], /^Vladivostok — .*21:00$/);
run("config.settings.language='ru'");
const copiedMeetingRu = run("meetingCopyText(Date.parse('2026-10-09T11:00:00Z'), [{key:'Europe/Moscow',zone:'Europe/Moscow'},{key:'Asia/Vladivostok',zone:'Asia/Vladivostok'}])");
assert.equal(copiedMeetingRu.split('\n').length, 2);
assert.doesNotMatch(copiedMeetingRu, /^Созвон/);
run("config.settings.language='en'");
assert.ok(run("contextAccessibility({availability:'dnd',solar:'night'}).includes(t('dnd'))"));
run("config.settings.language='en'");
assert.ok(run("contextAccessibility({availability:'dnd',solar:'night'}).includes(t('dnd'))"));
run("config.settings.language='ru'");
assert.equal(run("temporalBandHtml(new Date('2026-06-21T03:00:00Z'),'Asia/Tokyo').includes('solar-layer')"), false);
assert.ok(css.includes('grid-template-columns:minmax(0,1fr) 116px'));
assert.ok(css.includes('.city-clock{width:116px'));
assert.ok(css.includes('.temporal-marker{position:absolute;z-index:2;top:0;bottom:0;left:50%'));
assert.ok(css.includes('left:calc(-50% - var(--temporal-marker))'));
assert.ok(css.includes('.temporal-band{position:absolute;z-index:2;left:0;right:0'));
assert.ok(css.includes('.city-summary>.delete{position:absolute;z-index:3;top:50%'));
assert.ok(css.includes('.city-context{position:absolute;z-index:3;left:50%;bottom:11px'));
assert.ok(css.includes('.context-token:hover::after,.context-token:focus-visible::after'));
assert.ok(css.includes('grid-template-rows:0fr'));
assert.ok(css.includes('.expanded>.card-actions-wrap{grid-template-rows:1fr'));
assert.ok(css.includes('.card-actions{--card-actions-padding:10px'));
assert.ok(css.includes('grid-template-columns:1fr 1fr'));
assert.ok(css.includes('.clock>.card-actions-wrap>.card-actions{grid-template-columns:1fr}'));
assert.ok(css.includes('.base-summary{position:relative;min-width:0;padding:12px'));
assert.ok(css.includes('.clock{position:relative;height:150px;padding:0;'));
assert.equal(css.includes('--hero-min-height'), false);
assert.ok(css.includes('transition:height 220ms cubic-bezier(.25,.1,.25,1)'));
assert.ok(css.includes('.base-summary>.base-solar{position:absolute;z-index:3;top:12px;right:12px}'));
assert.ok(css.includes('.card-actions button{'));
assert.ok(css.includes('.quick-toggle[aria-expanded="true"] .quick-chevron-glyph{transform:rotate(180deg)}'));
assert.equal((css.match(/\.card-actions button\{/g) || []).length, 1);
assert.equal(css.includes('.base-expanded'), false);
assert.equal(css.includes('.city-expanded'), false);
assert.ok(css.includes('@media(prefers-reduced-motion:reduce)'));
assert.equal(run("t('alarmAction').endsWith('…') || t('changeCity').endsWith('…') || t('contactHours').endsWith('…')"), false);
assert.equal(run("solarStateAt(new Date('2026-06-21T03:00:00Z'), 35.6762, 139.6503)"), 'daylight');
assert.equal(run("solarStateAt(new Date('2026-06-21T15:00:00Z'), 35.6762, 139.6503)"), 'night');
assert.equal(run("solarStateAt(new Date('2026-09-15T14:41:00Z'), 21.0285, 105.8542)"), 'night');
assert.equal(run("solarStateAt(new Date('2026-09-16T01:41:00Z'), 21.0285, 105.8542)"), 'daylight');
assert.equal(run("solarZoneAliases.get('Asia/Saigon')"), 'Asia/Ho_Chi_Minh');
assert.ok(run("render.toString().includes('class=\"base-solar solar-glyph\"')"));
assert.equal(run("render.toString().includes('base-solar solar-glyph context-token')"), false);
assert.ok(run("updateDynamic.toString().includes(\"const baseSolar = temporalContext(selected, baseSolarKey()).solar\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"summary?.scrollHeight\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"actions?.scrollHeight\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"--card-actions-padding\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"actionsStyle.paddingTop\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"- currentPadding\")"));
assert.equal(run("applyExpandedBaseState.toString().includes('setTimeout')"), false);
assert.ok(fs.readFileSync(__dirname + '/ui/app.js', 'utf8').includes('const collapsedCard = interactiveTarget ? false : closeExpandedCardsOutside(event.target)'));
assert.ok(fs.readFileSync(__dirname + '/ui/app.js', 'utf8').includes("document.addEventListener('click', event => {"));
assert.equal(run("render.toString().includes('data-base-action=\"schedule\"')"), true);
assert.ok(run("render.toString().includes('class=\"card-actions-wrap\"')"));
assert.equal(run("render.toString().includes('base-expanded')"), false);
run("config = {timezones:[],settings:{theme:'dark',time_format:'24'}}; normalize()");
assert.equal(run("JSON.stringify(config.settings.availabilityDefault)"), JSON.stringify({okayStart:'07:00',workingStart:'09:00',workingEnd:'18:00',dndStart:'22:00'}));
assert.equal(run("JSON.stringify(config.cityContext)"), '{}');
run("config.cityContext.test = {label:'John',availabilityOverride:{okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}}; normalize()");
assert.equal(run("scheduleFor('test').workingStart"), '12:00');
assert.equal(run("baseSchedule().workingStart"), '09:00');
run("config.settings.baseAvailabilityOverride={okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}; normalize()");
assert.equal(run("baseSchedule().workingStart"), '12:00');
assert.equal(run("scheduleFor('test').workingStart"), '12:00');
assert.ok(run("scheduleEditorBody(defaultAvailability,{customizable:true,inherited:true,cityLabel:'John'}).includes('id=\"scheduleCityLabel\"')"));
assert.ok(run("scheduleEditorBody(defaultAvailability,{customizable:true,inherited:true}).includes('role=\"switch\"')"));
run("config.settings.top_clock_mode='manual'; config.settings.manual_top_timezone='America/New_York'; offset=2");
assert.ok(run("referenceTimestamp() - Date.now()") > 36e5);
assert.ok(run("referenceTimestamp() - Date.now()") <= 2 * 36e5);
assert.equal(run("offsetHours('America/New_York',new Date('2026-03-08T06:30:00Z'))"), -5);
assert.equal(run("offsetHours('America/New_York',new Date('2026-03-08T08:00:00Z'))"), -4);
run("config=structuredClone(defaults); normalize(); offset=0");
assert.equal(run("toggleExpandedCity('A')"), 'A');
assert.equal(run("toggleExpandedCity('B')"), 'B');
assert.equal(run("toggleExpandedCity('B')"), null);
assert.equal(run('toggleExpandedBase()'), true);
assert.equal(run('toggleExpandedBase()'), false);
run("expandedBase=true; closeExpandedCardsOutside({closest:selector => selector === '#baseClock' ? {} : null})");
assert.equal(run('expandedBase'), true);
run("closeExpandedCardsOutside({closest:() => null})");
assert.equal(run('expandedBase'), false);
run("expandedCityKey='A'; closeExpandedCardsOutside({closest:selector => selector === '.city-card' ? {dataset:{zone:'A'}} : null})");
assert.equal(run('expandedCityKey'), 'A');
run("closeExpandedCardsOutside({closest:() => null})");
assert.equal(run('expandedCityKey'), null);
run("let capturedBaseAlarm; openAlarmEditor = entry => {capturedBaseAlarm = entry}; config.settings.top_clock_mode='auto'; newAlarmForBase()");
assert.equal(run('capturedBaseAlarm.source_type'), 'base');
assert.equal(run('capturedBaseAlarm.base_kind'), 'auto');
assert.equal(run('capturedBaseAlarm.source_city_id'), null);
run("config.settings.top_clock_mode='manual'; config.settings.manual_top_timezone='America/New_York'; newAlarmForBase()");
assert.equal(run('capturedBaseAlarm.source_type'), 'base');
assert.equal(run('capturedBaseAlarm.base_kind'), 'manual');
assert.equal(run('capturedBaseAlarm.zone'), 'America/New_York');
assert.equal(run('capturedBaseAlarm.source_city_id'), 'America/New_York');
run("config.timezones=['A','B']; config.cityContext={A:{availabilityOverride:{okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}}}");
assert.equal(run("replaceCityAt(0,'C')"), true);
assert.equal(run("config.timezones.join()"), 'C,B');
assert.equal(run("Boolean(config.cityContext.A)"), false);
assert.equal(run("replaceCityAt(0,'B')"), false);
run("config=structuredClone(defaults); normalize(); offset=0");
run("config.settings.reminder_intervals = [30, 30, 60]; normalize()");
assert.equal(run('config.settings.reminder_intervals.join()'), '30,30,60');
run("render = () => {}; saveReminders = () => {}; offset = 2; globalThis.createdReminderId=createReminder('Asia/Almaty@@one', 15, 'Алматы'); offset = 2; createReminder('Asia/Almaty@@two', 15, 'Астана')");
assert.equal(run('createdReminderId'), run('reminders.entries[0].id'));
assert.equal(run('reminders.entries.length'), 2);
assert.equal(run('reminders.entries[0].city'), 'Алматы');
assert.equal(run('reminders.entries[1].city'), 'Астана');
assert.equal(run('offset'), 0);
assert.ok(run('reminders.entries.every(entry => entry.alarm === entry.target + entry.lead * 60 && entry.state === "pending")'));
run('config.settings.reminder_intervals = [7]; normalize()');
assert.equal(run('config.settings.reminder_intervals.join()'), '7');
run('config.settings.reminder_intervals = Array.from({length: 20}, (_, i) => i + 1); normalize()');
assert.equal(run('config.settings.reminder_intervals.length'), 20);
console.log('Native UI logic checks passed: time zones, DST, zero offset, interval preservation, city-bound reminders.');

run("window.innerHeight = 800; config.settings.hero_height = 300");
assert.equal(run('heroHeight()'), 300);
assert.equal(run('heroHeight(900)'), 450);
assert.equal(run('heroHeight(20)'), 136);
run(`(() => {
  const originalQuery = document.querySelector;
  const originalStyle = window.getComputedStyle;
  const values = {};
  const hero = {style:{setProperty:(key,value) => {values[key]=value;}}};
  const summary = {scrollHeight:141};
  const actions = {scrollHeight:100};
  const wrap = {firstElementChild:actions};
  const card = {querySelector:selector => selector === '.base-summary' ? summary : wrap};
  const resizer = {setAttribute(){}};
  document.querySelector = selector => ({'.hero':hero,'#baseClock':card,'#heroResizer':resizer})[selector];
  window.getComputedStyle = element => element === card
    ? {borderTopWidth:'1px',borderBottomWidth:'1px'}
    : element === actions
      ? {paddingTop:'10px',paddingBottom:'10px',getPropertyValue:() => '10px'}
      : {borderTopWidth:'1px',borderBottomWidth:'0px'};
  config.settings.hero_height = 136;
  expandedBase = true;
  syncHeroHeight();
  const opened = {...values};
  expandedBase = false;
  syncHeroHeight();
  globalThis.heroSizingResult = {opened,closed:{...values}};
  document.querySelector = originalQuery;
  window.getComputedStyle = originalStyle;
})()`);
assert.equal(run('heroSizingResult.opened["--hero-size"]'), '244px');
assert.equal(run('heroSizingResult.closed["--hero-size"]'), '143px');
assert.equal(run('Object.hasOwn(heroSizingResult.opened,"--hero-min-height")'), false);
run("Date.now = () => 1800000000000");
assert.equal(run('reminderRemaining({alarm: 1800000061})'), '1:01');
assert.equal(run('reminderRemaining({alarm: 1800003661})'), '1:01:01');
assert.equal(run('reminderRemaining({alarm: 1799999999})'), '0:00');
assert.equal(run('reminderProgress({started_at: 1799999940, alarm: 1800000060})'), 50);
run(`
  const alarmRoot = {innerHTML: '', scrollTop: 0};
  const alarmHeading = {};
  document.querySelector = selector => selector === '#alarmList' ? alarmRoot : selector === '#savedHeading' ? alarmHeading : null;
  config.settings.top_clock_mode = 'manual';
  config.settings.manual_top_timezone = 'Asia/Kathmandu';
  reminders.entries = [{id:'test', state:'pending', city:'Tokyo', zone:'Asia/Tokyo', target:1800000000, alarm:1800003600, started_at:1800000000}];
  renderAlarms();
`);
assert.ok(run("alarmRoot.innerHTML.includes(timeAt(new Date(1800003600000), 'Asia/Tokyo') + '</span></div>')"));
assert.ok(run("alarmRoot.innerHTML.includes('<span>' + timeAt(new Date(1800003600000), 'Asia/Kathmandu') + '</span>')"));
assert.ok(run("alarmRoot.innerHTML.includes('class=\"progress-time\"')"));
assert.ok(!run("alarmRoot.innerHTML.includes('⌛') || alarmRoot.innerHTML.includes('◷')"));
console.log('Reminder countdown, city/base alarm times and section height checks passed.');

run(`
  byKey.set('Asia/Almaty@@one', {key:'Asia/Almaty@@one', en:'Almaty', ru:'Алматы'});
  byKey.set('Asia/Almaty@@two', {key:'Asia/Almaty@@two', en:'Astana', ru:'Астана'});
  reminders.entries = [
    {id:'later', city_key:'Asia/Almaty@@one', zone:'Asia/Almaty', alarm:1800007200, state:'pending'},
    {id:'other', city_key:'Asia/Almaty@@two', zone:'Asia/Almaty', alarm:1800003600, state:'pending'},
    {id:'legacy', city:'Алматы', zone:'Asia/Almaty', alarm:1800003600, state:'ringing'},
    {id:'done', city_key:'Asia/Almaty@@one', alarm:1800003600, state:'done'}
  ];
`);
assert.equal(run("cityReminders('Asia/Almaty@@one').map(e => e.id).join()"), 'legacy,later');
assert.equal(run("cityReminders('Asia/Almaty@@two').map(e => e.id).join()"), 'other');
run("reminders.entries = reminders.entries.filter(e => e.id !== 'legacy'); reminders.entries[0].alarm += 300");
assert.equal(run("cityReminders('Asia/Almaty@@one')[0].alarm"), 1800007500);
assert.equal(run("cityReminders('Asia/Tokyo').length"), 0);
console.log('Per-city reminder checks passed: multiple alarms, same-zone cities, legacy names, snooze and removal.');

run("config.settings.reminder_intervals = [-20000, -1, 0, 1, 20000]; normalize()");
assert.equal(run('config.settings.reminder_intervals.join()'), '-20000,-1,0,1,20000');
assert.equal(run('intervalValue(intervalValue(1 - 1) - 1)'), -1);
assert.equal(run('intervalValue(intervalValue(-1 + 1) + 1)'), 1);
assert.equal(run('intervalCaption(-15)'), '−15 мин');
assert.equal(run('intervalCaption(15)'), '+15 мин');
assert.equal(run('intervalCaption(0, 1800003600000)'), run('timeAt(new Date(1800003600000), baseZone())'));
assert.equal(run('alarmTimestamp(1800003600000, -15)'), 1800002700000);
assert.equal(run('alarmTimestamp(1800003600000, 0)'), 1800003600000);
assert.equal(run('alarmTimestamp(1800003600000, 15)'), 1800004500000);
assert.equal(run('validAlarm(1800003600000, -61)'), false);
assert.equal(run('validAlarm(1800003600000, -15)'), true);
run("referenceTimestamp = () => Date.now() + offset * 3600000; reminders.entries = []; offset = 3; createReminder('Asia/Tokyo', -15, 'Tokyo'); offset = 3; createReminder('Asia/Tokyo', 0, 'Tokyo'); offset = 3; createReminder('Asia/Tokyo', 15, 'Tokyo')");
assert.equal(run('reminders.entries.length'), 3);
assert.equal(run('reminders.entries.map(e => e.alarm - e.target).join()'), '-900,0,900');
run(`
  const dropElement = {classList:{remove(){}}};
  document.body = {classList:{remove(){}}};
  bindReminderDrop(dropElement, 'Asia/Tokyo', 'Tokyo');
  offset = 4;
  dropElement.ondrop({dataTransfer:{types:['lead'],getData:()=> '0'},preventDefault(){}});
`);
assert.equal(run('reminders.entries.length'), 4);
assert.equal(run('reminders.entries[3].alarm'), run('reminders.entries[3].target'));
console.log('Signed interval checks passed: zero crossing, persistence, captions, before/at/after, past rejection, zero drag/drop.');

run(`
  let editorNodes = {}, editorTimes = [];
  document.querySelector = selector => editorNodes[selector] || null;
  document.querySelectorAll = selector => selector === '[data-schedule-time]' ? editorTimes : [];
  modal = (_title, body) => {
    editorTimes = ['okayStart','workingStart','workingEnd','dndStart'].map(key => ({dataset:{scheduleTime:key},value:'',disabled:false}));
    const schedule = config.settings.availabilityDefault;
    editorTimes.forEach(input => input.value = schedule[input.dataset.scheduleTime]);
    const inherited = body.includes('id="useDefaultSwitch" role="switch" aria-checked="true"');
    const attrs = {'aria-checked':String(inherited)};
    editorNodes = {
      '#useDefaultSwitch': body.includes('id="useDefaultSwitch"') ? {getAttribute:key => attrs[key],setAttribute:(key,value) => attrs[key]=value,classList:{toggle(){}},addEventListener(_name,handler){this.click=handler}} : null,
      '#scheduleCityLabel': {value:'Alice'}, '#scheduleError': {textContent:''}, '#saveSchedule': {},
    };
  };
  saveConfig = () => {}; render = () => {}; closeModal = () => {}; openCityActions = () => {}; openSettings = () => {};
  config=structuredClone(defaults); config.cityContext['Asia/Vladivostok']={label:'Old'};
  openScheduleEditor('Asia/Vladivostok','card');
  editorNodes['#saveSchedule'].onclick();
`);
assert.equal(run("config.cityContext['Asia/Vladivostok'].label"), 'Alice');
assert.equal(run("config.cityContext['Asia/Vladivostok'].availabilityOverride"), undefined);
run(`
  openScheduleEditor(baseScheduleKey,'base');
  editorNodes['#useDefaultSwitch'].click();
  editorTimes[1].value='10:00';
  editorNodes['#saveSchedule'].onclick();
`);
assert.equal(run('baseSchedule().workingStart'), '10:00');
assert.equal(run("scheduleFor('Asia/Vladivostok').workingStart"), '09:00');
run(`openScheduleEditor(baseScheduleKey,'base'); editorNodes['#useDefaultSwitch'].click(); editorNodes['#saveSchedule'].onclick()`);
assert.equal(run('config.settings.baseAvailabilityOverride'), null);
console.log('Contact hour editor checks passed: city label, base override and default switch.');

run(`
  let settingsMenu = '';
  modal = (_title, body) => {
    settingsMenu = body;
    editorNodes = {'#baseSchedule':{},'#typicalSchedule':{}};
  };
  config.timezones = ['Asia/Vladivostok'];
  openCitySettingsList();
`);
assert.equal(run("settingsMenu.includes('id=\"selectBaseCity\"')"), false);
assert.ok(run("settingsMenu.includes('id=\"baseSchedule\"')"));
assert.ok(run("settingsMenu.includes('id=\"typicalSchedule\"')"));
assert.ok(run("settingsMenu.includes('data-city-settings=\"Asia/Vladivostok\"')"));
console.log('Settings navigation checks passed: base chooser on main screen and grouped schedules.');

run(`
  let quickVisible = false, toggleHidden = false, expandedValue = '';
  document.body = {classList:{toggle(){}}};
  document.querySelector = selector => ({
    '#quickSection': {classList:{toggle:(_name,value) => quickVisible=value}},
    '#quickToggle': {classList:{toggle:(_name,value) => toggleHidden=value},setAttribute:(_name,value) => expandedValue=value},
  })[selector] || null;
  offset=0; quickAtNowOpen=false; pendingLead=null;
  toggleQuickAtNow();
`);
assert.equal(run('offset'), 0);
assert.equal(run('quickVisible'), true);
assert.equal(run('expandedValue'), 'true');
run('beginReminder(15)');
assert.equal(run('pendingLead'), 15);
run('pendingLead=null; toggleQuickAtNow()');
assert.equal(run('quickVisible'), false);
assert.equal(run('expandedValue'), 'false');
run("quickAtNowOpen=true; reminders.entries=[]; createReminder('Asia/Tokyo',15,'Tokyo')");
assert.equal(run('reminders.entries[0].alarm - reminders.entries[0].target'), 900);
assert.ok(Math.abs(run('reminders.entries[0].target * 1000') - Date.now()) < 2000);
run('quickAtNowOpen=false; offset=2; updateQuickVisibility(); toggleQuickAtNow()');
assert.equal(run('quickVisible'), true);
assert.equal(run('toggleHidden'), true);
assert.equal(run('quickAtNowOpen'), false);
console.log('Quick reminder disclosure checks passed: zero-offset selection, toggle and chevron state.');
run(`meetingMode=true; quickAtNowOpen=true; offset=3; liveOffset=3; pendingLead=15;
  meetingSelected=new Set(['Europe/Moscow']); meetingResult={at:1}; meetingEarlier={at:2}; meetingShowingEarlier=true;
  resetTimeline();`);
assert.equal(run('offset'), 0);
assert.equal(run('liveOffset'), null);
assert.equal(run('quickAtNowOpen'), false);
assert.equal(run('meetingMode'), false);
assert.equal(run('meetingSelected.size'), 0);
assert.equal(run('meetingResult'), null);
assert.equal(run('meetingEarlier'), null);
assert.equal(run('meetingShowingEarlier'), false);
assert.equal(run('pendingLead'), null);
assert.equal(run('quickVisible'), false);
assert.equal(run('expandedValue'), 'false');
assert.ok(run("bindMain.toString().includes('oncontextmenu = event => { event.preventDefault(); resetTimeline(); }')"));
console.log('Timeline right-click reset clears meeting selection, reminders and offset.');
assert.equal(run("newerVersion('v1.1.130', 'v1.1.129 macOS Beta')"), true);
assert.equal(run("newerVersion('v1.1.128', 'v1.1.129')"), false);
assert.equal(run("newerVersion('invalid', 'v1.1.129')"), false);
assert.match(appSource, /id="versionButton"/);
assert.match(appSource, /id="updateButton"/);
assert.match(css, /\.update-button::after\{white-space:nowrap/);
console.log('Feature entry and icon update control checks passed.');
assert.equal(run('featureGuideItems().length'), 17);
assert.equal(run('new Set(featureGuideItems().map(item => item[0])).size'), 17);
assert.ok(run("featureGuideItems().some(item => item[0] === 'reminderNow')"));
assert.ok(run("featureGuideItems().some(item => item[0] === 'reminderFuture')"));
assert.ok(run("featureGuideItems().some(item => item[0] === 'reminderDrag')"));
assert.ok(run("featureGuideItems().some(item => item[0] === 'reminderScroll')"));
assert.ok(run("featureGuideItems().some(item => item[0] === 'reminderExact')"));
run('modal=(title,body)=>{window.featureGuideBody=body}');
run('openFeatureGuide()');
assert.match(context.window.featureGuideBody, /<details class="feature-group"/);
assert.match(context.window.featureGuideBody, /Показать в интерфейсе/);
assert.equal((context.window.featureGuideBody.match(/data-feature=/g) || []).length, 17);
assert.doesNotMatch(context.window.featureGuideBody, /feature-preview/);
assert.doesNotMatch(css, /\.feature-preview/);
assert.doesNotMatch(context.window.featureGuideBody, /feature-intro[^>]*style=.*border/);
assert.match(css, /\.feature-intro\{padding:0 1px 5px\}/);
const guideNodes = new Map();
context.window.innerHeight = 800;
context.document.querySelector = selector => {
  if (!guideNodes.has(selector)) guideNodes.set(selector, {
    classList: {added: new Set(), add(name) {this.added.add(name);}, remove(name) {this.added.delete(name);}},
    getBoundingClientRect: () => ({top: 300}), scrollIntoView() {}, innerHTML:'', className:''
  });
  return guideNodes.get(selector);
};
run("showFeatureInApp('timeline')");
assert.ok(guideNodes.get('#sliderArea').classList.added.has('feature-tour-focus'));
assert.match(guideNodes.get('#featureTour').innerHTML, /Передвиньте ползунок/);
run('openFeatureGuide()');
assert.equal(guideNodes.get('#sliderArea').classList.added.size, 0);
console.log('Interactive feature guide routes to controls and returns cleanly.');
run(`window.__tickProbe={visual:0,due:0};
  updateDynamic=()=>window.__tickProbe.visual++;
  updateLiveCityTimes=()=>window.__tickProbe.visual++;
  updateAlarmDetail=()=>window.__tickProbe.visual++;
  checkDue=()=>window.__tickProbe.due++;
  checkForUpdates=()=>{};
  window.nativeTick(false);
  window.nativeTick(true);`);
assert.equal(context.window.__tickProbe.visual, 3);
assert.equal(context.window.__tickProbe.due, 2);
console.log('Hidden tick keeps reminder checks and skips visual refresh.');
run(`reminders={lead:15,entries:[]}; platform='windows'; window.__wakeMessages=[];
  window.chrome.webview.postMessage=message=>window.__wakeMessages.push(message);`);
const wakeNow = Date.parse('2026-10-07T06:00:00Z');
assert.equal(run(`backgroundTickDelay(${wakeNow})`), 60000);
run(`reminders.entries=[{state:'pending',alarm:${(wakeNow + 5000) / 1000}}]`);
assert.equal(run(`backgroundTickDelay(${wakeNow})`), 5000);
run(`reminders.entries=[{state:'pending',alarm:${(wakeNow - 5000) / 1000}}]`);
assert.equal(run(`backgroundTickDelay(${wakeNow})`), 1000);
run(`reminders.entries=[{state:'pending',alarm:${(wakeNow + 120000) / 1000}}]`);
assert.equal(run(`backgroundTickDelay(${wakeNow})`), 60000);
run(`reminders.entries=[{state:'ringing',alarm:${(wakeNow + 120000) / 1000}}]`);
assert.equal(run(`backgroundTickDelay(${wakeNow})`), 1000);
run('reminders.entries=[]; scheduleBackgroundTick()');
assert.equal(context.window.__wakeMessages.at(-1), 'scheduleTick\n60000');
run('platform="macos"; scheduleBackgroundTick()');
assert.equal(context.window.__wakeMessages.length, 2);
assert.equal(context.window.__wakeMessages.at(-1), 'scheduleTick\n60000');
console.log('Background wake scheduling preserves due checks on Windows and macOS.');
