const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const nodes = new Map();
const node = () => ({innerHTML:'',textContent:'',value:'',hidden:false,dataset:{},style:{},isConnected:true,scrollTop:0,listeners:{},scrollTo({top}){this.scrollTop=top;this.onscroll?.();},classList:{toggle(){},remove(){},add(){}},querySelectorAll(){return [];},querySelector(){return null;},addEventListener(type,fn,options){this.listeners[type]={fn,options};},setAttribute(name,value){this[name]=value;},getAttribute(name){return this[name];},focus(){this.focused=true;}});
const get = selector => {if (!nodes.has(selector)) nodes.set(selector,node()); return nodes.get(selector);};
const FixedDate = class extends Date {constructor(...args){super(...(args.length ? args : ['2026-09-10T12:00:00Z']));} static now(){return Date.parse('2026-09-10T12:00:00Z');}};
const scheduled=new Map();let nextScheduled=1;
const context = vm.createContext({setTimeout:fn=>{const id=nextScheduled++;scheduled.set(id,fn);return id;},clearTimeout:id=>scheduled.delete(id),requestAnimationFrame:fn=>{const id=nextScheduled++;scheduled.set(id,fn);return id;},cancelAnimationFrame:id=>scheduled.delete(id),performance:{now:()=>0},window:{chrome:{webview:{postMessage(){},addEventListener(){}}},innerWidth:417,innerHeight:750},document:{querySelector:get,querySelectorAll:()=>[],addEventListener(){},body:{classList:{toggle(){}}}},Date:FixedDate,Intl,structuredClone,crypto:require('node:crypto').webcrypto});
for(const file of ['reminder_ui.js','app.js']) vm.runInContext(fs.readFileSync(__dirname+'/ui/'+file,'utf8'),context);
const run = script => vm.runInContext(script,context);
const setPicker=(selector,value)=>{const root=get(selector);const numeric=selector==='#alarmDate'?Date.parse(value+'T00:00:00Z')/86400000:+value;const current=selector==='#alarmDate'?Date.parse(root.value+'T00:00:00Z')/86400000:+root.value;root.scrollTop+=(numeric-current)*40;root.onscroll();};
const scrollPicker=(selector,delta)=>{const root=get(selector);root.scrollTop+=delta;root.onscroll();};
run(`normalize(); const legacy = {id:'legacy',zone:'Asia/Bangkok',city:'Бангкок, Джакарта, Ханой',alarm:1799668800,target:1799668800,state:'pending'}; syncReminderModel(legacy);`);
assert.equal(run('legacy.source_type'),'base');
assert.equal(run('legacy.source_city_id'),null);
assert.equal(run('legacy.id'),'legacy');
assert.equal(run('legacy.alarm'),1799668800);
assert.equal(run('sourceCaption(legacy)'),'Базовое время (Windows)');
assert.equal(run('legacy.timezone_id'),'Asia/Bangkok');
assert.ok(run('legacy.active'));
assert.equal(run("compactAlarmDate(new Date('2026-09-10T23:30:00Z'),'Asia/Tokyo')"),'Завтра');
assert.equal(run("compactAlarmDate(new Date('2026-09-10T23:30:00Z'),'America/New_York')"),'Сегодня');
assert.match(run("compactAlarmDate(new Date('2027-01-10T10:00:00Z'),'Asia/Tokyo')"),/2027/);
run(`const entries = [1,2,3,4,5].map(n=>({id:String(n),zone:'Asia/Tokyo',alarm:Date.now()/1000+n*86400,state:'pending'})); const labels={innerHTML:'',querySelectorAll:()=>[],querySelector:()=>null}; renderAlarmLabels(labels,entries);`);
assert.equal((run('labels.innerHTML').match(/data-label-alarm=/g)||[]).length,2);
assert.match(run('labels.innerHTML'),/>\+3</);
run(`reminders.entries=[{id:'city',city:'Токио',city_key:'Asia/Tokyo',zone:'Asia/Tokyo',source_type:'city',title:'Созвон',alarm:Date.parse('2026-09-11T11:00:00Z')/1000,target:Date.parse('2026-09-11T10:00:00Z')/1000,state:'pending'}]; syncReminderModel(reminders.entries[0]);`);
run("showAlarmDetail('city')");
assert.match(get('#modal').innerHTML,/id="editTitle" value="Созвон"/);
assert.match(get('#modal').innerHTML,/id="dailySwitch" role="switch" aria-checked="false"/);
assert.ok(get('#modal').innerHTML.includes('id="alarmHour"'));
assert.ok(!get('#modal').innerHTML.includes('id="editDetail"'));
assert.ok(!get('#modal').innerHTML.includes('leadStepper'));
run("editAlarm('city')");
assert.ok(get('#modal').innerHTML.includes('schedule-wheels'));
assert.ok(get('#alarmHour').innerHTML.includes('schedule-option'));
assert.ok(!get('#modal').innerHTML.includes('target-steps'));
setPicker('#alarmHour','23'); scrollPicker('#alarmHour',40);
assert.equal(+get('#alarmHour').value,0);
setPicker('#alarmMinute','0'); scrollPicker('#alarmMinute',-40);
assert.equal(+get('#alarmMinute').value,59);
get('#alarmDate').value='2026-09-12'; get('#alarmHour').value='9'; get('#alarmMinute').value='30'; get('#editTitle').value='Новая встреча';
get('#dailySwitch').setAttribute('aria-checked','false');
get('#saveAlarm').onclick();
assert.equal(run('reminders.entries[0].alarm'),Date.parse('2026-09-12T00:30:00Z')/1000);
assert.equal(run('reminders.entries[0].local_date'),'2026-09-12');
assert.equal(run('reminders.entries[0].local_time'),'09:30');
assert.equal(run('reminders.entries[0].title'),'Новая встреча');
assert.equal(run('reminders.entries[0].id'),'city');
assert.equal(run('reminders.entries[0].timezone_id'),'Asia/Tokyo');
run("offset=6; openAlarmForCity('Europe/Moscow')");
assert.equal(run('offset'),6);
assert.equal(run('reminders.entries.length'),1);
assert.ok(get('#modal').innerHTML.includes('Новое напоминание'));
assert.ok(get('#modal').innerHTML.includes(run("cityName('Europe/Moscow')")));
assert.ok(!get('#modal').innerHTML.includes('Удалить напоминание'));
assert.equal(+get('#alarmHour').value,15);
assert.equal(+get('#alarmMinute').value,1);
setPicker('#alarmDate','2026-09-11'); get('#alarmHour').value='16'; get('#alarmMinute').value='05'; get('#editTitle').value='Москва — созвон';
get('#dailySwitch').setAttribute('aria-checked','true');
get('#saveAlarm').onclick();
assert.equal(run('offset'),6);
assert.equal(run('reminders.entries.length'),2);
assert.equal(run('reminders.entries[1].city_key'),'Europe/Moscow');
assert.equal(run('reminders.entries[1].timezone_id'),'Europe/Moscow');
assert.equal(run('reminders.entries[1].title'),'Москва — созвон');
assert.equal(run('reminders.entries[1].repeat'),'daily');
assert.equal(run('reminders.entries[1].repeat_time'),'16:05');
assert.equal(run("nextDailyAlarm(reminders.entries[1], Date.parse('2026-09-11T13:05:00Z'))"),Date.parse('2026-09-12T13:05:00Z')/1000);
assert.equal(run("nextDailyAlarm({zone:'America/New_York',repeat_time:'09:00'}, Date.parse('2027-03-13T14:00:00Z'))"),Date.parse('2027-03-14T13:00:00Z')/1000);
assert.equal(run("nextDailyAlarm({zone:'America/New_York',repeat_time:'02:30'}, Date.parse('2027-03-14T00:00:00Z'))"),Date.parse('2027-03-15T06:30:00Z')/1000);
run("reminders.entries[1].alarm=Date.parse('2026-09-11T14:05:00Z')/1000; syncReminderModel(reminders.entries[1])");
assert.equal(run('reminders.entries[1].repeat_time'),'16:05');
run('reminders.entries.pop()');
run("config.settings.quick_titles = []; rememberTitle('Моё название'); rememberTitle('Моё название')");
assert.equal(run('config.settings.quick_titles.length'),1);
assert.equal(run('config.settings.quick_titles[0].use_count'),2);
get('#namePopover').firstElementChild={style:{},offsetHeight:300};
run("showNamePopover('city',400,700)");
get('#customTitle').onclick(); assert.ok(get('#newAlarmTitle').focused);
get('#newAlarmTitle').value='Такси домой'; get('#nameForm').onsubmit({preventDefault(){}});
assert.equal(run('reminders.entries[0].title'),'Такси домой');
assert.equal(run('config.settings.quick_titles.length'),2);
assert.equal(get('#namePopover').innerHTML,'');
run("showNamePopover('city',0,0); closeNamePopover()");
assert.equal(run('reminders.entries.length'),1);
run("reminders.entries[0].title=''; showAlarmDetail('city')");
assert.ok(!get('#modal').innerHTML.includes('<h3>'));
console.log('Reminder UX checks passed: legacy migration, timezone dates, capped labels, details, absolute-time editing, picker wrap, optional naming and saved titles.');

run("config.settings.quick_titles = [{id:'custom',title:'Мой вариант'}]; delete config.settings.title_library_version; normalize()");
assert.equal(run('config.settings.quick_titles.length'),7);
run('config.settings.quick_titles.splice(1); normalize()');
assert.equal(run('config.settings.quick_titles.length'),1);
run("showNamePopover('city',0,0)");
assert.ok(get('#namePopover').innerHTML.includes('name-success'));
assert.ok(get('#namePopover').innerHTML.includes('Мой вариант'));
assert.ok(!get('#namePopover').innerHTML.includes('Созвон'));
console.log('Unified editable title library and direct editing checks passed.');

run("editAlarm('city')");
setPicker('#alarmDate','2026-12-31'); scrollPicker('#alarmDate',40);
assert.equal(get('#alarmDate').value,'2027-01-01');
setPicker('#alarmDate','2028-02-28'); scrollPicker('#alarmDate',40);
assert.equal(get('#alarmDate').value,'2028-02-29');
setPicker('#alarmDate',get('#alarmDate').value); scrollPicker('#alarmDate',40);
assert.equal(get('#alarmDate').value,'2028-03-01');
setPicker('#alarmMinute','58'); get('#alarmMinute').onkeydown({preventDefault(){},key:'PageDown'});
assert.equal(+get('#alarmMinute').value,3);
setPicker('#alarmDate','2026-09-10');setPicker('#alarmHour','0');setPicker('#alarmMinute','0');
setPicker('#alarmMinute',get('#alarmMinute').value); scrollPicker('#alarmMinute',40);
assert.equal(get('#saveAlarm').disabled,true);
const before = run('reminders.entries[0].alarm');
get('#cancelAlarm').onclick(); assert.equal(run('reminders.entries[0].alarm'),before);
run("reminders.entries[0].zone='America/New_York'; editAlarm('city')");
setPicker('#alarmDate','2027-03-14');setPicker('#alarmHour','2');setPicker('#alarmMinute','29');
setPicker('#alarmMinute',get('#alarmMinute').value); scrollPicker('#alarmMinute',40);
assert.equal(get('#saveAlarm').disabled,true);
assert.ok(get('#scheduleError').textContent.includes('недоступно'));
console.log('Schedule wheels: year/leap-day transitions, keyboard, past-time and DST validation, cancel passed.');

const wheel = get('#alarmMinute');
assert.equal(wheel.onwheel,undefined); assert.equal(wheel.listeners.wheel.options.passive,true);
setPicker('#alarmMinute','0'); const initial=wheel.scrollTop;
scrollPicker('#alarmMinute',7.5);assert.equal(wheel.scrollTop,initial+7.5); // fractional position preserved, no snap per event
scrollPicker('#alarmMinute',392.5);assert.equal(+wheel.value,10); // a flick spans many rows
assert.equal(scheduled.size,0);wheel.listeners.wheel.fn({});assert.equal(scheduled.size,0); // native wheel adds no artificial inertia
wheel.setPointerCapture=()=>{};wheel.hasPointerCapture=()=>true;wheel.releasePointerCapture=()=>{};wheel.getBoundingClientRect=()=>({top:0});
wheel.onpointerdown({pointerType:'mouse',button:0,pointerId:1,clientY:100,timeStamp:0});
wheel.onpointermove({clientY:20,timeStamp:16});wheel.onscroll();
const releasePosition=wheel.scrollTop;
wheel.onpointerup({pointerId:1,clientY:20,timeStamp:17});assert.equal(scheduled.size,1);
let now=0;for(let i=0;i<200&&scheduled.size;i++){now+=16;const list=[...scheduled.values()];scheduled.clear();for(const fn of list)fn(now);}
assert.ok(wheel.scrollTop>releasePosition+40);assert.equal(wheel.scrollTop%40,0);assert.equal(scheduled.size,0);
assert.ok(run('pickerDecay(3,16).velocity')<3);
assert.ok(run('pickerDecay(3,16).distance')>run('pickerDecay(.1,16).distance'));
let scalar=0,continuous=0,commits=0;const control=node();context.control=control;context.scalarOptions={read:()=>scalar,write:value=>scalar=value,paint:value=>continuous=value,finish:()=>commits++};run('bindValueScroll(control,scalarOptions)');
const wheelEvent=(dy,mode=0,wheelDeltaY)=>control.onwheel({deltaY:dy,deltaMode:mode,wheelDeltaY,preventDefault(){},stopPropagation(){}});
wheelEvent(-7);assert.equal(scalar,0);assert.equal(continuous,.175);
wheelEvent(-393);assert.equal(scalar,10); // full distance, no speed gate
for(const dy of [-20,-12,-8])wheelEvent(dy);assert.equal(scalar,11); // native decaying tail remains intact
const flush=()=>{const list=[...scheduled.values()];scheduled.clear();for(const fn of list)fn();};flush();assert.equal(scalar,11);assert.equal(commits,1);assert.equal(scheduled.size,0);
wheelEvent(100,0,-120);assert.equal(scalar,10); // one physical mouse-wheel detent is exactly one value
wheelEvent(-100,0,120);assert.equal(scalar,11);flush();
wheelEvent(6,1);assert.equal(scalar,9);flush();
wheelEvent(1,2);assert.equal(scalar,4);flush();
wheelEvent(2000);assert.equal(scalar,-46);flush(); // signed zero crossing and fast multi-value input
let quarter=0;const shiftControl=node();context.shiftControl=shiftControl;context.shiftOptions={read:()=>quarter,write:value=>quarter=value,stepForEvent:event=>event.shiftKey?.25:1};run('bindValueScroll(shiftControl,shiftOptions)');
shiftControl.onwheel({deltaY:-100,deltaMode:0,wheelDeltaY:120,shiftKey:true,preventDefault(){},stopPropagation(){}});assert.equal(quarter,.25);flush();
shiftControl.onwheel({deltaY:-100,deltaMode:0,wheelDeltaY:120,shiftKey:false,preventDefault(){},stopPropagation(){}});assert.equal(quarter,1.25);flush();
console.log('Native fractional scroll, multi-row flick, no double wheel inertia, mouse deceleration and shared numeric scrolling passed.');
run("editAlarm('city')");assert.ok(!get('#modal').innerHTML.includes('wheelSensitivity'));assert.ok(!get('#modal').innerHTML.includes('schedule-hint'));
run("config.settings.quick_titles=Array.from({length:15},(_,i)=>({title:'Title '+i}));editAlarm('city')");
assert.equal((get('#modal').innerHTML.match(/data-editor-title=/g)||[]).length,16);
const chooseTitle = index => get('#editorTitleChoices').onclick({target:{closest:()=>({dataset:{editorTitle:String(index)}})}});
chooseTitle(14);assert.equal(get('#editTitle').value,'Title 14');
chooseTitle(-1);assert.equal(get('#editTitle').value,'');
get('#editTitle').value='Manual title';get('#editTitle').oninput();assert.equal(get('#editTitle').value,'Manual title');
assert.notEqual(run('reminders.entries[0].title'),'Manual title'); // drafts do not persist until Save
console.log('All title choices and draft isolation passed.');

const scrollBeforeTouch = wheel.scrollTop;
wheel.onpointerdown({pointerType:'touch',button:0,pointerId:2,clientY:100,timeStamp:500});
wheel.onpointercancel();assert.equal(wheel.scrollTop,scrollBeforeTouch);assert.equal(scheduled.size,0);
const positionBeforeRecentering = +wheel.value;
wheel.scrollTop += 60*40*6;wheel.onscrollend();assert.equal(+wheel.value,positionBeforeRecentering);assert.equal(wheel.scrollTop,(60*20+positionBeforeRecentering)*40);
wheel.isConnected=false;wheel.onpointercancel();assert.equal(scheduled.size,0);
console.log('Native touch cancellation and cyclic recentering passed.');

const alarmRoot=get('#alarmList');let replacements=0,markup=alarmRoot.innerHTML;
Object.defineProperty(alarmRoot,'innerHTML',{get:()=>markup,set:value=>{markup=value;replacements++;},configurable:true});
run('renderAlarms()');const firstRender=replacements;
const progress={style:{}},countdown={textContent:''};
alarmRoot.querySelectorAll=()=>[{dataset:{alarm:'city'},querySelector:selector=>selector==='.progress i'?progress:countdown}];
run('renderAlarms();renderAlarms()');assert.equal(replacements,firstRender);
assert.ok(countdown.textContent.length>0);assert.ok(progress.style.width.endsWith('%'));
run("reminders.entries[0].title='Updated';renderAlarms()");assert.equal(replacements,firstRender+1);assert.ok(markup.includes('Updated'));
run('reminders.entries=[];renderAlarms()');assert.ok(markup.includes('empty'));
console.log('Second ticks preserve alarm list DOM and update countdown/progress; edits and removal still refresh.');

run("reminders.entries=[{id:'daily',zone:'Asia/Tokyo',city:'Токио',source_type:'city',alarm:Date.parse('2026-09-10T11:00:00Z')/1000,target:Date.parse('2026-09-10T11:00:00Z')/1000,repeat:'daily',repeat_time:'20:00',state:'pending'}]; syncReminderModel(reminders.entries[0]); checkDue()");
assert.equal(run('reminders.entries[0].state'),'ringing');
get('#snooze').onclick();
assert.equal(run('reminders.entries[0].repeat_time'),'20:00');
run("reminders.entries[0].alarm=Date.parse('2026-09-10T11:00:00Z')/1000; checkDue()");
get('#ack').onclick();
assert.equal(run('reminders.entries.length'),1);
assert.equal(run('reminders.entries[0].state'),'pending');
assert.equal(run('reminders.entries[0].alarm'),Date.parse('2026-09-11T11:00:00Z')/1000);
run("reminders.entries[0].repeat='none'; reminders.entries[0].alarm=Date.parse('2026-09-10T11:00:00Z')/1000; checkDue()");
get('#ack').onclick();
assert.equal(run('reminders.entries.length'),0);
console.log('Daily alarms survive snooze and acknowledgment at the same local time; one-time alarms are removed.');
