const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({
  window: {chrome: {webview: {postMessage() {}, addEventListener() {}}}},
  document: {querySelector: () => ({}), querySelectorAll: () => [], addEventListener() {}},
  Intl, Date, structuredClone, crypto: require('node:crypto').webcrypto,
});
vm.runInContext(fs.readFileSync(__dirname + '/ui/suncalc.js', 'utf8'), context);
vm.runInContext(fs.readFileSync(__dirname + '/ui/reminder_ui.js', 'utf8'), context);
vm.runInContext(fs.readFileSync(__dirname + '/ui/app.js', 'utf8'), context);
const run = script => vm.runInContext(script, context);
const css = fs.readFileSync(__dirname + '/ui/style.css', 'utf8');
assert.equal(run('strings.ru.citySettings'), 'График в городах');
assert.equal(run('strings.en.citySettings'), 'Schedules by city');
assert.equal(run('hotkeyLabel()'), 'Alt+Shift+T');
assert.equal(run("hotkeyLabel({modifiers:2,key:112})"), 'Ctrl+F1');
assert.equal(run("hotkeyLabel({modifiers:0,key:65})"), 'A');
assert.equal(run("hotkeyFromEvent({code:'KeyK',key:'л',ctrlKey:true,altKey:false,shiftKey:true,metaKey:false})?.key"), 75);
assert.equal(run("hotkeyFromEvent({code:'F11',key:'F11',ctrlKey:false,altKey:false,shiftKey:false,metaKey:false})?.key"), 122);
assert.equal(run("hotkeyFromEvent({code:'F12',key:'F12',ctrlKey:false,altKey:false,shiftKey:false,metaKey:false})"), null);
assert.equal(run("hotkeyFromEvent({code:'KeyT',key:'t',ctrlKey:false,altKey:false,shiftKey:false,metaKey:true})"), null);
assert.equal(run("offsetHours('Asia/Kolkata', new Date('2026-09-05T00:00:00Z'))"), 5.5);
assert.equal(run("offsetHours('Asia/Kathmandu', new Date('2026-09-05T00:00:00Z'))"), 5.75);
assert.equal(run("epochAt('2026-09-05T12:15', 'Asia/Kathmandu')"), Date.parse('2026-09-05T06:30:00Z'));
assert.equal(run("epochAt('2026-01-05T12:00', 'America/New_York')"), Date.parse('2026-01-05T17:00:00Z'));
assert.equal(run("epochAt('2026-07-05T12:00', 'America/New_York')"), Date.parse('2026-07-05T16:00:00Z'));
assert.ok(Math.abs(run('referenceTimestamp()') - Date.now()) < 1000);
assert.equal(run('sliderPosition(0, 400)'), 10);
assert.equal(run('sliderPosition(6, 400)'), 105);
assert.equal(run('sliderPosition(12, 400)'), 200);
assert.equal(run('sliderPosition(24, 400)'), 390);
assert.equal(run('shiftCaption(.25)'), '+15 мин');
assert.equal(run('shiftCaption(4.5)'), '+4 ч 30 мин');
assert.equal(run("availabilityAt(defaultAvailability, 7 * 60)"), 'okay');
assert.equal(run("availabilityAt(defaultAvailability, 9 * 60)"), 'working');
assert.equal(run("availabilityAt(defaultAvailability, 18 * 60)"), 'okay');
assert.equal(run("availabilityAt(defaultAvailability, 22 * 60)"), 'dnd');
assert.equal(run("availabilityAt({okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}, 30)"), 'okay');
assert.equal(run("availabilityAt({okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}, 120)"), 'dnd');
assert.ok(run("contextAccessibility({availability:'dnd',solar:'night'}).includes(t('dnd'))"));
run("config.settings.language='en'");
assert.ok(run("contextAccessibility({availability:'dnd',solar:'night'}).includes(t('dnd'))"));
run("config.settings.language='ru'");
assert.equal(run("temporalBandHtml(new Date('2026-06-21T03:00:00Z'),'Asia/Tokyo').includes('solar-layer')"), false);
assert.ok(css.includes('grid-template-columns:minmax(0,1fr) 116px'));
assert.ok(css.includes('.city-clock{width:116px'));
assert.ok(css.includes('.temporal-marker{position:absolute;z-index:2;top:0;bottom:0;left:50%'));
assert.ok(css.includes('left:calc(-50% - var(--temporal-marker))'));
assert.ok(css.includes('.temporal-band{position:absolute;z-index:2;left:0;right:0'));
assert.ok(css.includes('.city-summary>.delete{position:absolute;z-index:3;top:50%'));
assert.ok(css.includes('.city-context{position:absolute;z-index:3;left:50%;bottom:11px'));
assert.ok(css.includes('.context-token:hover::after,.context-token:focus-visible::after'));
assert.ok(css.includes('grid-template-rows:0fr'));
assert.ok(css.includes('.expanded>.card-actions-wrap{grid-template-rows:1fr'));
assert.ok(css.includes('.card-actions{--card-actions-padding:10px'));
assert.ok(css.includes('grid-template-columns:1fr 1fr'));
assert.ok(css.includes('.clock>.card-actions-wrap>.card-actions{grid-template-columns:1fr}'));
assert.ok(css.includes('.base-summary{position:relative;min-width:0;padding:12px'));
assert.ok(css.includes('.clock{position:relative;height:150px;padding:0;'));
assert.equal(css.includes('--hero-min-height'), false);
assert.ok(css.includes('transition:height 220ms cubic-bezier(.25,.1,.25,1)'));
assert.ok(css.includes('.base-summary>.base-solar{position:absolute;z-index:3;top:12px;right:12px}'));
assert.ok(css.includes('.card-actions button{'));
assert.equal((css.match(/\.card-actions button\{/g) || []).length, 1);
assert.equal(css.includes('.base-expanded'), false);
assert.equal(css.includes('.city-expanded'), false);
assert.ok(css.includes('@media(prefers-reduced-motion:reduce)'));
assert.equal(run("t('alarmAction').endsWith('…') || t('changeCity').endsWith('…') || t('contactHours').endsWith('…')"), false);
assert.equal(run("solarStateAt(new Date('2026-06-21T03:00:00Z'), 35.6762, 139.6503)"), 'daylight');
assert.equal(run("solarStateAt(new Date('2026-06-21T15:00:00Z'), 35.6762, 139.6503)"), 'night');
assert.equal(run("solarStateAt(new Date('2026-09-15T14:41:00Z'), 21.0285, 105.8542)"), 'night');
assert.equal(run("solarStateAt(new Date('2026-09-16T01:41:00Z'), 21.0285, 105.8542)"), 'daylight');
assert.equal(run("solarZoneAliases.get('Asia/Saigon')"), 'Asia/Ho_Chi_Minh');
assert.ok(run("render.toString().includes('class=\"base-solar solar-glyph\"')"));
assert.equal(run("render.toString().includes('base-solar solar-glyph context-token')"), false);
assert.ok(run("updateDynamic.toString().includes(\"const baseSolar = temporalContext(selected, baseSolarKey()).solar\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"summary?.scrollHeight\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"actions?.scrollHeight\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"--card-actions-padding\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"actionsStyle.paddingTop\")"));
assert.ok(run("syncHeroHeight.toString().includes(\"- currentPadding\")"));
assert.equal(run("applyExpandedBaseState.toString().includes('setTimeout')"), false);
assert.ok(fs.readFileSync(__dirname + '/ui/app.js', 'utf8').includes('const collapsedCard = interactiveTarget ? false : closeExpandedCardsOutside(event.target)'));
assert.ok(fs.readFileSync(__dirname + '/ui/app.js', 'utf8').includes("document.addEventListener('click', event => {"));
assert.equal(run("render.toString().includes('data-base-action=\"schedule\"')"), false);
assert.ok(run("render.toString().includes('class=\"card-actions-wrap\"')"));
assert.equal(run("render.toString().includes('base-expanded')"), false);
run("config = {timezones:[],settings:{theme:'dark',time_format:'24'}}; normalize()");
assert.equal(run("JSON.stringify(config.settings.availabilityDefault)"), JSON.stringify({okayStart:'07:00',workingStart:'09:00',workingEnd:'18:00',dndStart:'22:00'}));
assert.equal(run("JSON.stringify(config.cityContext)"), '{}');
run("config.cityContext.test = {label:'John',availabilityOverride:{okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}}; normalize()");
assert.equal(run("scheduleFor('test').workingStart"), '12:00');
run("config.settings.top_clock_mode='manual'; config.settings.manual_top_timezone='America/New_York'; offset=2");
assert.ok(run("referenceTimestamp() - Date.now()") > 36e5);
assert.ok(run("referenceTimestamp() - Date.now()") <= 2 * 36e5);
assert.equal(run("offsetHours('America/New_York',new Date('2026-03-08T06:30:00Z'))"), -5);
assert.equal(run("offsetHours('America/New_York',new Date('2026-03-08T08:00:00Z'))"), -4);
run("config=structuredClone(defaults); normalize(); offset=0");
assert.equal(run("toggleExpandedCity('A')"), 'A');
assert.equal(run("toggleExpandedCity('B')"), 'B');
assert.equal(run("toggleExpandedCity('B')"), null);
assert.equal(run('toggleExpandedBase()'), true);
assert.equal(run('toggleExpandedBase()'), false);
run("expandedBase=true; closeExpandedCardsOutside({closest:selector => selector === '#baseClock' ? {} : null})");
assert.equal(run('expandedBase'), true);
run("closeExpandedCardsOutside({closest:() => null})");
assert.equal(run('expandedBase'), false);
run("expandedCityKey='A'; closeExpandedCardsOutside({closest:selector => selector === '.city-card' ? {dataset:{zone:'A'}} : null})");
assert.equal(run('expandedCityKey'), 'A');
run("closeExpandedCardsOutside({closest:() => null})");
assert.equal(run('expandedCityKey'), null);
run("let capturedBaseAlarm; openAlarmEditor = entry => {capturedBaseAlarm = entry}; config.settings.top_clock_mode='auto'; newAlarmForBase()");
assert.equal(run('capturedBaseAlarm.source_type'), 'base');
assert.equal(run('capturedBaseAlarm.base_kind'), 'auto');
assert.equal(run('capturedBaseAlarm.source_city_id'), null);
run("config.settings.top_clock_mode='manual'; config.settings.manual_top_timezone='America/New_York'; newAlarmForBase()");
assert.equal(run('capturedBaseAlarm.source_type'), 'base');
assert.equal(run('capturedBaseAlarm.base_kind'), 'manual');
assert.equal(run('capturedBaseAlarm.zone'), 'America/New_York');
assert.equal(run('capturedBaseAlarm.source_city_id'), 'America/New_York');
run("config.timezones=['A','B']; config.cityContext={A:{availabilityOverride:{okayStart:'10:00',workingStart:'12:00',workingEnd:'20:00',dndStart:'01:00'}}}");
assert.equal(run("replaceCityAt(0,'C')"), true);
assert.equal(run("config.timezones.join()"), 'C,B');
assert.equal(run("Boolean(config.cityContext.A)"), false);
assert.equal(run("replaceCityAt(0,'B')"), false);
run("config=structuredClone(defaults); normalize(); offset=0");
run("config.settings.reminder_intervals = [30, 30, 60]; normalize()");
assert.equal(run('config.settings.reminder_intervals.join()'), '30,30,60');
run("render = () => {}; saveReminders = () => {}; offset = 2; globalThis.createdReminderId=createReminder('Asia/Almaty@@one', 15, 'Алматы'); offset = 2; createReminder('Asia/Almaty@@two', 15, 'Астана')");
assert.equal(run('createdReminderId'), run('reminders.entries[0].id'));
assert.equal(run('reminders.entries.length'), 2);
assert.equal(run('reminders.entries[0].city'), 'Алматы');
assert.equal(run('reminders.entries[1].city'), 'Астана');
assert.equal(run('offset'), 0);
assert.ok(run('reminders.entries.every(entry => entry.alarm === entry.target + entry.lead * 60 && entry.state === "pending")'));
run('config.settings.reminder_intervals = [7]; normalize()');
assert.equal(run('config.settings.reminder_intervals.join()'), '7');
run('config.settings.reminder_intervals = Array.from({length: 20}, (_, i) => i + 1); normalize()');
assert.equal(run('config.settings.reminder_intervals.length'), 20);
console.log('Native UI logic checks passed: time zones, DST, zero offset, interval preservation, city-bound reminders.');

run("window.innerHeight = 800; config.settings.hero_height = 300");
assert.equal(run('heroHeight()'), 300);
assert.equal(run('heroHeight(900)'), 450);
assert.equal(run('heroHeight(20)'), 136);
run(`(() => {
  const originalQuery = document.querySelector;
  const originalStyle = window.getComputedStyle;
  const values = {};
  const hero = {style:{setProperty:(key,value) => {values[key]=value;}}};
  const summary = {scrollHeight:141};
  const actions = {scrollHeight:100};
  const wrap = {firstElementChild:actions};
  const card = {querySelector:selector => selector === '.base-summary' ? summary : wrap};
  const resizer = {setAttribute(){}};
  document.querySelector = selector => ({'.hero':hero,'#baseClock':card,'#heroResizer':resizer})[selector];
  window.getComputedStyle = element => element === card
    ? {borderTopWidth:'1px',borderBottomWidth:'1px'}
    : element === actions
      ? {paddingTop:'10px',paddingBottom:'10px',getPropertyValue:() => '10px'}
      : {borderTopWidth:'1px',borderBottomWidth:'0px'};
  config.settings.hero_height = 136;
  expandedBase = true;
  syncHeroHeight();
  const opened = {...values};
  expandedBase = false;
  syncHeroHeight();
  globalThis.heroSizingResult = {opened,closed:{...values}};
  document.querySelector = originalQuery;
  window.getComputedStyle = originalStyle;
})()`);
assert.equal(run('heroSizingResult.opened["--hero-size"]'), '244px');
assert.equal(run('heroSizingResult.closed["--hero-size"]'), '143px');
assert.equal(run('Object.hasOwn(heroSizingResult.opened,"--hero-min-height")'), false);
run("Date.now = () => 1800000000000");
assert.equal(run('reminderRemaining({alarm: 1800000061})'), '1:01');
assert.equal(run('reminderRemaining({alarm: 1800003661})'), '1:01:01');
assert.equal(run('reminderRemaining({alarm: 1799999999})'), '0:00');
assert.equal(run('reminderProgress({started_at: 1799999940, alarm: 1800000060})'), 50);
run(`
  const alarmRoot = {innerHTML: '', scrollTop: 0};
  const alarmHeading = {};
  document.querySelector = selector => selector === '#alarmList' ? alarmRoot : selector === '#savedHeading' ? alarmHeading : null;
  config.settings.top_clock_mode = 'manual';
  config.settings.manual_top_timezone = 'Asia/Kathmandu';
  reminders.entries = [{id:'test', state:'pending', city:'Tokyo', zone:'Asia/Tokyo', target:1800000000, alarm:1800003600, started_at:1800000000}];
  renderAlarms();
`);
assert.ok(run("alarmRoot.innerHTML.includes(timeAt(new Date(1800003600000), 'Asia/Tokyo') + '</span></div>')"));
assert.ok(run("alarmRoot.innerHTML.includes('<span>' + timeAt(new Date(1800003600000), 'Asia/Kathmandu') + '</span>')"));
assert.ok(run("alarmRoot.innerHTML.includes('class=\"progress-time\"')"));
assert.ok(!run("alarmRoot.innerHTML.includes('⌛') || alarmRoot.innerHTML.includes('◷')"));
console.log('Reminder countdown, city/base alarm times and section height checks passed.');

run(`
  byKey.set('Asia/Almaty@@one', {key:'Asia/Almaty@@one', en:'Almaty', ru:'Алматы'});
  byKey.set('Asia/Almaty@@two', {key:'Asia/Almaty@@two', en:'Astana', ru:'Астана'});
  reminders.entries = [
    {id:'later', city_key:'Asia/Almaty@@one', zone:'Asia/Almaty', alarm:1800007200, state:'pending'},
    {id:'other', city_key:'Asia/Almaty@@two', zone:'Asia/Almaty', alarm:1800003600, state:'pending'},
    {id:'legacy', city:'Алматы', zone:'Asia/Almaty', alarm:1800003600, state:'ringing'},
    {id:'done', city_key:'Asia/Almaty@@one', alarm:1800003600, state:'done'}
  ];
`);
assert.equal(run("cityReminders('Asia/Almaty@@one').map(e => e.id).join()"), 'legacy,later');
assert.equal(run("cityReminders('Asia/Almaty@@two').map(e => e.id).join()"), 'other');
run("reminders.entries = reminders.entries.filter(e => e.id !== 'legacy'); reminders.entries[0].alarm += 300");
assert.equal(run("cityReminders('Asia/Almaty@@one')[0].alarm"), 1800007500);
assert.equal(run("cityReminders('Asia/Tokyo').length"), 0);
console.log('Per-city reminder checks passed: multiple alarms, same-zone cities, legacy names, snooze and removal.');

run("config.settings.reminder_intervals = [-20000, -1, 0, 1, 20000]; normalize()");
assert.equal(run('config.settings.reminder_intervals.join()'), '-20000,-1,0,1,20000');
assert.equal(run('intervalValue(intervalValue(1 - 1) - 1)'), -1);
assert.equal(run('intervalValue(intervalValue(-1 + 1) + 1)'), 1);
assert.equal(run('intervalCaption(-15)'), '−15 мин');
assert.equal(run('intervalCaption(15)'), '+15 мин');
assert.equal(run('intervalCaption(0, 1800003600000)'), run('timeAt(new Date(1800003600000), baseZone())'));
assert.equal(run('alarmTimestamp(1800003600000, -15)'), 1800002700000);
assert.equal(run('alarmTimestamp(1800003600000, 0)'), 1800003600000);
assert.equal(run('alarmTimestamp(1800003600000, 15)'), 1800004500000);
assert.equal(run('validAlarm(1800003600000, -61)'), false);
assert.equal(run('validAlarm(1800003600000, -15)'), true);
run("referenceTimestamp = () => Date.now() + offset * 3600000; reminders.entries = []; offset = 3; createReminder('Asia/Tokyo', -15, 'Tokyo'); offset = 3; createReminder('Asia/Tokyo', 0, 'Tokyo'); offset = 3; createReminder('Asia/Tokyo', 15, 'Tokyo')");
assert.equal(run('reminders.entries.length'), 3);
assert.equal(run('reminders.entries.map(e => e.alarm - e.target).join()'), '-900,0,900');
run(`
  const dropElement = {classList:{remove(){}}};
  document.body = {classList:{remove(){}}};
  bindReminderDrop(dropElement, 'Asia/Tokyo', 'Tokyo');
  offset = 4;
  dropElement.ondrop({dataTransfer:{types:['lead'],getData:()=> '0'},preventDefault(){}});
`);
assert.equal(run('reminders.entries.length'), 4);
assert.equal(run('reminders.entries[3].alarm'), run('reminders.entries[3].target'));
console.log('Signed interval checks passed: zero crossing, persistence, captions, before/at/after, past rejection, zero drag/drop.');
